import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { AppConfig } from '../../config/configuration';
import { DomainRepository } from './domain.repository';

const CERT_ROOT = '/etc/ssl/ems';

/**
 * Generates the nginx server blocks that route wildcard subdomains and every
 * live custom domain to the API/storefront upstream — inspectable/downloadable
 * text, the same `RawResponse` pattern as `SeoService.generateSitemap`.
 *
 * **Boundary, stated plainly:** this only generates config text. Actually
 * loading it into a running nginx (or an ALB's listener rules) and syncing
 * certificate bytes from `StoragePort` to `/etc/ssl/ems/...` on the
 * TLS-terminating host is a deploy-time/infra job outside this backend
 * repo's scope, the same reason storefront rendering itself is out of
 * scope for this phase.
 */
@Injectable()
export class NginxConfigService {
  private readonly app: AppConfig;

  constructor(
    configService: ConfigService,
    private readonly domains: DomainRepository,
  ) {
    this.app = configService.getOrThrow<AppConfig>('app');
  }

  async generate(): Promise<string> {
    const liveCustomDomains = await this.domains.findAllLiveCustomDomains();

    const blocks = [this.wildcardBlock(), ...liveCustomDomains.map((d) => this.customDomainBlock(d.tenantId, d.hostname))];

    return [
      `# Generated by NginxConfigService — do not edit by hand.`,
      `# Regenerate via GET /v1/console/domains/nginx-config after any custom domain change.`,
      '',
      ...blocks,
    ].join('\n');
  }

  private wildcardBlock(): string {
    const domain = this.app.rootDomain;
    return [
      `server {`,
      `    listen 443 ssl;`,
      `    server_name *.${domain};`,
      `    ssl_certificate     ${CERT_ROOT}/wildcard/${domain}/fullchain.pem;`,
      `    ssl_certificate_key ${CERT_ROOT}/wildcard/${domain}/privkey.pem;`,
      `    location / {`,
      `        proxy_pass http://ems_upstream;`,
      `        proxy_set_header Host $host;`,
      `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
      `        proxy_set_header X-Forwarded-Proto $scheme;`,
      `    }`,
      `}`,
      '',
    ].join('\n');
  }

  private customDomainBlock(tenantId: string, hostname: string): string {
    return [
      `server {`,
      `    listen 443 ssl;`,
      `    server_name ${hostname};`,
      `    ssl_certificate     ${CERT_ROOT}/${tenantId}/${hostname}/fullchain.pem;`,
      `    ssl_certificate_key ${CERT_ROOT}/${tenantId}/${hostname}/privkey.pem;`,
      `    location / {`,
      `        proxy_pass http://ems_upstream;`,
      `        proxy_set_header Host $host;`,
      `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
      `        proxy_set_header X-Forwarded-Proto $scheme;`,
      `    }`,
      `}`,
      '',
    ].join('\n');
  }
}
