#!/usr/bin/env node
/**
 * Generates an RS256 keypair for JWT signing and an AES-256 encryption key,
 * printed as the exact `JWT_PRIVATE_KEY_BASE64`/`JWT_PUBLIC_KEY_BASE64`/
 * `ENCRYPTION_KEY_BASE64` values `configuration.ts` decodes
 * (`Buffer.from(env.JWT_PRIVATE_KEY_BASE64, 'base64').toString('utf8')` — a
 * base64'd PEM, not a base64'd DER or raw key), so pasting this output
 * straight into `.env` (or a Kubernetes Secret — see
 * `infra/k8s/secret.yaml.example`) just works.
 *
 * Never run against a `.env` that's actually deployed anywhere: this always
 * generates a *new* keypair, and rotating `JWT_PRIVATE_KEY_BASE64` without
 * also bumping `JWT_KEY_ID` invalidates every refresh token currently
 * outstanding (`RefreshTokenService`/`JwksController` key rotation, docs/01 §5).
 */
import { generateKeyPairSync, randomBytes } from 'node:crypto';

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

const encryptionKey = randomBytes(32); // ENCRYPTION_KEY_BASE64 — env.schema.ts requires >= 32 bytes

console.log('# Generated by scripts/generate-keys.mjs — paste into .env or a Secret. Do not commit.');
console.log(`JWT_PRIVATE_KEY_BASE64=${Buffer.from(privateKey, 'utf8').toString('base64')}`);
console.log(`JWT_PUBLIC_KEY_BASE64=${Buffer.from(publicKey, 'utf8').toString('base64')}`);
console.log(`ENCRYPTION_KEY_BASE64=${encryptionKey.toString('base64')}`);
console.log('# Remember to also set a non-"dev-"-prefixed JWT_KEY_ID in production (env.schema.ts refuses to boot otherwise).');
