/**
 * The ONE registry of API error codes (docs/04-api-conventions.md §10).
 *
 * Clients branch on `code`, never on `message` — messages are free to be
 * reworded or localized. Each code carries its HTTP status here so the mapping
 * lives in exactly one place instead of being re-decided at every throw site.
 */
export const ErrorCode = {
  // --- Validation ---------------------------------------------------------
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',

  // --- Authentication -----------------------------------------------------
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID_CODE: 'AUTH_MFA_INVALID_CODE',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',

  // --- Authorization ------------------------------------------------------
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  // Never surfaced as itself — mapped to RESOURCE_NOT_FOUND at the boundary so
  // a probe cannot confirm the row exists (docs/04 §3).
  CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',

  // --- Billing ------------------------------------------------------------
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_NOT_ACTIVE',
  PLAN_QUOTA_EXCEEDED: 'PLAN_QUOTA_EXCEEDED',
  PLAN_FEATURE_UNAVAILABLE: 'PLAN_FEATURE_UNAVAILABLE',

  // --- Generic resource ---------------------------------------------------
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_GONE: 'RESOURCE_GONE',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',

  // --- Catalog ------------------------------------------------------------
  PRODUCT_SKU_DUPLICATE: 'PRODUCT_SKU_DUPLICATE',
  PRODUCT_NOT_PUBLISHABLE: 'PRODUCT_NOT_PUBLISHABLE',
  CATEGORY_CYCLE_DETECTED: 'CATEGORY_CYCLE_DETECTED',

  // --- Inventory ----------------------------------------------------------
  INVENTORY_INSUFFICIENT: 'INVENTORY_INSUFFICIENT',
  INVENTORY_RESERVATION_EXPIRED: 'INVENTORY_RESERVATION_EXPIRED',

  // --- Orders -------------------------------------------------------------
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_ALREADY_FULFILLED: 'ORDER_ALREADY_FULFILLED',
  ORDER_EMPTY: 'ORDER_EMPTY',
  CART_EMPTY: 'CART_EMPTY',

  // --- Payments -----------------------------------------------------------
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  REFUND_EXCEEDS_PAYMENT: 'REFUND_EXCEEDS_PAYMENT',

  // --- Marketing ----------------------------------------------------------
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_LIMIT_REACHED: 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_NOT_ELIGIBLE: 'COUPON_NOT_ELIGIBLE',

  // --- Shipping -----------------------------------------------------------
  SHIPPING_CARRIER_ERROR: 'SHIPPING_CARRIER_ERROR',
  SHIPPING_PINCODE_UNSERVICEABLE: 'SHIPPING_PINCODE_UNSERVICEABLE',

  // --- Domains ------------------------------------------------------------
  DOMAIN_ALREADY_TAKEN: 'DOMAIN_ALREADY_TAKEN',
  DOMAIN_VERIFICATION_FAILED: 'DOMAIN_VERIFICATION_FAILED',
  DOMAIN_RESERVED: 'DOMAIN_RESERVED',

  // --- Channels -----------------------------------------------------------
  CHANNEL_TOKEN_EXPIRED: 'CHANNEL_TOKEN_EXPIRED',
  CHANNEL_SYNC_FAILED: 'CHANNEL_SYNC_FAILED',

  // --- Platform / transport ----------------------------------------------
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Canonical HTTP status per code. Anything unlisted falls back to 500. */
export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 422,
  MALFORMED_REQUEST: 400,

  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_REVOKED: 401,
  AUTH_REFRESH_TOKEN_REUSED: 401,
  AUTH_ACCOUNT_LOCKED: 423,
  AUTH_EMAIL_NOT_VERIFIED: 403,
  // 200: an MFA challenge is a successful step in the login flow, not a failure.
  AUTH_MFA_REQUIRED: 200,
  AUTH_MFA_INVALID_CODE: 401,
  AUTH_OTP_INVALID: 401,
  AUTH_OTP_EXPIRED: 401,

  PERMISSION_DENIED: 403,
  TENANT_SUSPENDED: 403,
  TENANT_CONTEXT_MISSING: 400,
  // 404, deliberately: see docs/04 §3.
  CROSS_TENANT_ACCESS: 404,

  SUBSCRIPTION_PAST_DUE: 402,
  SUBSCRIPTION_NOT_ACTIVE: 402,
  PLAN_QUOTA_EXCEEDED: 402,
  PLAN_FEATURE_UNAVAILABLE: 402,

  RESOURCE_NOT_FOUND: 404,
  RESOURCE_CONFLICT: 409,
  RESOURCE_GONE: 410,
  VERSION_MISMATCH: 409,
  BUSINESS_RULE_VIOLATION: 422,
  INVARIANT_VIOLATION: 500,
  CONCURRENT_MODIFICATION: 409,

  PRODUCT_SKU_DUPLICATE: 409,
  PRODUCT_NOT_PUBLISHABLE: 422,
  CATEGORY_CYCLE_DETECTED: 422,

  INVENTORY_INSUFFICIENT: 409,
  INVENTORY_RESERVATION_EXPIRED: 410,

  ORDER_NOT_CANCELLABLE: 409,
  ORDER_ALREADY_FULFILLED: 409,
  ORDER_EMPTY: 422,
  CART_EMPTY: 422,

  PAYMENT_GATEWAY_ERROR: 502,
  PAYMENT_ALREADY_CAPTURED: 409,
  PAYMENT_SIGNATURE_INVALID: 401,
  REFUND_EXCEEDS_PAYMENT: 422,

  COUPON_EXPIRED: 422,
  COUPON_USAGE_LIMIT_REACHED: 422,
  COUPON_NOT_ELIGIBLE: 422,

  SHIPPING_CARRIER_ERROR: 502,
  SHIPPING_PINCODE_UNSERVICEABLE: 422,

  DOMAIN_ALREADY_TAKEN: 409,
  DOMAIN_VERIFICATION_FAILED: 422,
  DOMAIN_RESERVED: 409,

  CHANNEL_TOKEN_EXPIRED: 409,
  CHANNEL_SYNC_FAILED: 502,

  IDEMPOTENCY_KEY_REUSED: 409,
  RATE_LIMIT_EXCEEDED: 429,
  REQUEST_TIMEOUT: 504,
  EXTERNAL_SERVICE_ERROR: 502,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};

export function statusForErrorCode(code: string): number {
  return ERROR_STATUS[code as ErrorCode] ?? 500;
}

export const ERROR_DOCS_BASE_URL = 'https://docs.ems.app/errors';

export function docsUrlForErrorCode(code: string): string {
  return `${ERROR_DOCS_BASE_URL}/${code}`;
}
