import type { TenantSpec } from '../types';
import { axis, colourAxis, STAFF_TEMPLATE, standardCoupons } from './common';

/** DecorNest Home: wall art, lighting, soft furnishings, vases, kitchen and dining decor. Fictional brands. */
export const DECORNEST: TenantSpec = {
  slug: 'decornest-home',
  tag: 'DNH',
  businessName: 'DecorNest Home',
  legalName: 'DecorNest Home Living Private Limited',
  gstin: '08DECOR0005E1Z4',
  storefrontTheme: 'default',
  themeTemplate: 'furniture',
  brandColor: '8a5a44',
  accentColor: 'c2410c',
  tagline: 'Make every corner feel like home',
  storeName: 'DecorNest Home',
  contactPhone: '+917000055001',
  supportPhone: '+917000055002',
  reviewNoun: 'piece',
  homeStateShare: 0.2,
  weekendBoost: 1.3,
  freeShippingRupees: 1299,
  shippingRupees: 129,
  paymentMix: [['CARD', 30], ['UPI', 32], ['COD', 20], ['EMI', 8], ['NETBANKING', 10]],
  lineMix: [[1, 52], [2, 28], [3, 14], [4, 6]],
  qtyMix: [[1, 70], [2, 22], [3, 6], [4, 2]],
  staff: STAFF_TEMPLATE([['Anita', 'Shekhawat'], ['Rohan', 'Purohit'], ['Kavita', 'Rathore'], ['Dev', 'Bhardwaj'], ['Shreya', 'Khandelwal'], ['Manav', 'Sethi']]),
  warehouses: [
    { code: 'WH-JAI-01', name: 'Jaipur Home Decor Warehouse', line1: 'Plot 44, Sitapura Industrial Area', city: 'Jaipur', state: 'Rajasthan', stateCode: 'RJ', postal: '302022', lat: '26.7790000', lng: '75.8310000' },
    { code: 'WH-MUM-01', name: 'Mumbai West Hub', line1: 'Unit 18, Vasai Logistics Park', city: 'Vasai', state: 'Maharashtra', stateCode: 'MH', postal: '401208', lat: '19.4000000', lng: '72.8300000' },
  ],
  brands: [
    { slug: 'casalume', name: 'Casalume', description: 'Lamps and lighting with a warm glow.' },
    { slug: 'artisana', name: 'Artisana', description: 'Wall art and handcrafted accents.' },
    { slug: 'weavora', name: 'Weavora', description: 'Cushions, curtains and rugs in soft textures.' },
    { slug: 'claycraft', name: 'Claycraft', description: 'Ceramic vases and tableware.' },
    { slug: 'dwellmate', name: 'Dwellmate', description: 'Kitchen and dining essentials.' },
    { slug: 'woodnest', name: 'Woodnest', description: 'Wooden shelves, trays and accents.' },
    { slug: 'glowcraft', name: 'Glowcraft', description: 'Decorative lights and lanterns.' },
    { slug: 'scentora', name: 'Scentora', description: 'Candles, diffusers and incense.' },
    { slug: 'greenleaf-living', name: 'Greenleaf Living', description: 'Planters and artificial greenery.' },
    { slug: 'hearthstyle', name: 'Hearthstyle', description: 'Mirrors, clocks and showpieces.' },
  ],
  categories: [
    { slug: 'wall-decor', name: 'Wall Decor', description: 'Art, mirrors and clocks for every wall.', children: [
      { slug: 'wall-art', name: 'Wall Art', description: 'Framed prints, canvas and metal wall art.' },
      { slug: 'wall-mirrors-clocks', name: 'Mirrors & Clocks', description: 'Decorative mirrors and wall clocks.' },
    ] },
    { slug: 'lighting', name: 'Lighting', description: 'Lamps and decorative lights.', children: [
      { slug: 'table-floor-lamps', name: 'Table & Floor Lamps', description: 'Lamps for reading and ambience.' },
      { slug: 'pendant-string-lights', name: 'Pendant & String Lights', description: 'Pendants, fairy lights and lanterns.' },
    ] },
    { slug: 'soft-furnishings', name: 'Soft Furnishings', description: 'Cushions, curtains and rugs.', children: [
      { slug: 'cushions-covers', name: 'Cushions & Covers', description: 'Cushion covers and filled cushions.' },
      { slug: 'curtains', name: 'Curtains', description: 'Door and window curtains.' },
      { slug: 'rugs-carpets', name: 'Rugs & Carpets', description: 'Rugs and carpets in many sizes.' },
    ] },
    { slug: 'vases-planters', name: 'Vases & Planters', description: 'Ceramic vases and planters.', children: [
      { slug: 'vases', name: 'Vases', description: 'Ceramic, glass and metal vases.' },
      { slug: 'planters', name: 'Planters & Greenery', description: 'Pots, planters and artificial plants.' },
    ] },
    { slug: 'kitchen-dining', name: 'Kitchen & Dining', description: 'Tableware and serveware.', children: [
      { slug: 'dinnerware', name: 'Dinnerware', description: 'Dinner sets, plates and bowls.' },
      { slug: 'drinkware-serveware', name: 'Drinkware & Serveware', description: 'Glasses, mugs, trays and jars.' },
    ] },
    { slug: 'accents', name: 'Home Accents', description: 'Candles, fragrance and showpieces.', children: [
      { slug: 'candles-fragrance', name: 'Candles & Fragrance', description: 'Scented candles, diffusers and incense.' },
      { slug: 'showpieces', name: 'Showpieces & Organisers', description: 'Figurines, trays, frames and shelves.' },
    ] },
  ],
  families: [
    { id: 'WAL', category: 'wall-art', count: 18, type: 'SIMPLE', brands: ['artisana', 'woodnest'], gst: 12, hsn: '9701', price: [499, 6999], ending: 99, weightG: [400, 4500], dimsMm: [600, 450, 30], popularity: 1.6, stock: [10, 60], palette: ['44403c', 'e7e5e4'],
      models: ['Framed Abstract Art Set of 3|1299-2999', 'Canvas Landscape Print|999-2499', 'Metal Tree of Life Wall Art|1499-3499', 'Macrame Wall Hanging|799-1999', 'Botanical Prints Set of 4|899-2199', 'Wooden Wall Panel|1999-4999', 'Madhubani Style Painting|1299-3499', 'Gold Foil Leaf Wall Art|1499-3999', 'Large Canvas Triptych|2999-6999'],
      specs: { Material: ['Canvas', 'Metal', 'Wood', 'Cotton cord'], Size: ['Small', 'Medium', 'Large'], Style: ['Modern', 'Traditional', 'Boho'] }, facets: ['Style'],
      blurb: '{name} gives an empty wall instant character.', bullets: ['Ready-to-hang with fittings', 'Fade-resistant inks', 'Wipe with a dry cloth', '7-day easy returns'] },
    { id: 'MIR', category: 'wall-mirrors-clocks', count: 14, type: 'SIMPLE', brands: ['hearthstyle', 'woodnest'], gst: 18, hsn: '7009', price: [399, 7999], ending: 99, weightG: [800, 7000], popularity: 1.2, stock: [8, 50], palette: ['27272a', 'd4d4d8'],
      models: ['Round Wall Mirror|1299-3499', 'Arched Full Length Mirror|3999-7999', 'Sunburst Mirror|1999-4499', 'Wooden Frame Mirror|1499-3299', 'Silent Wall Clock Round|499-1299', 'Pendulum Wall Clock|1499-3499', 'Industrial Wall Clock|899-2199'],
      specs: { Shape: ['Round', 'Rectangular', 'Arched'], Frame: ['Metal', 'Wood', 'Frameless'] }, facets: ['Shape'],
      blurb: '{name} brightens a room and makes it feel larger.', bullets: ['Shatter-resistant backing', 'Easy wall mounting', 'Wipe clean', '7-day easy returns'] },
    { id: 'LMP', category: 'table-floor-lamps', count: 16, type: 'SIMPLE', brands: ['casalume', 'glowcraft'], gst: 18, hsn: '9405', price: [699, 8999], ending: 99, weightG: [600, 6500], popularity: 1.5, stock: [10, 70], palette: ['78350f', 'fde68a'],
      models: ['Ceramic Table Lamp|1299-2999', 'Bedside Touch Lamp|899-1999', 'Arc Floor Lamp|3499-7999', 'Tripod Floor Lamp|3999-8999', 'Rattan Table Lamp|1499-3299', 'Study Desk Lamp LED|699-1799', 'Marble Base Lamp|2499-5999', 'Fabric Shade Floor Lamp|2999-6999'],
      specs: { Bulb: ['E27 bulb included', 'Integrated LED', 'E14 bulb not included'], Material: ['Ceramic', 'Metal', 'Rattan', 'Marble'] }, facets: ['Material'],
      blurb: '{name} adds a warm, welcoming glow to your space.', bullets: ['Energy-saving LED compatible', 'Stable base', 'Switch on cord', '7-day easy returns'] },
    { id: 'PEN', category: 'pendant-string-lights', count: 14, type: 'SIMPLE', brands: ['glowcraft', 'casalume'], gst: 18, hsn: '9405', price: [249, 6999], ending: 99, weightG: [200, 4500], popularity: 1.4, stock: [10, 80], palette: ['422006', 'fed7aa'],
      models: ['Fairy String Lights 10 m|299-799', 'Rattan Pendant Light|1499-3499', 'Brass Pendant Cluster|3999-6999', 'Paper Lantern Set of 3|499-1299', 'Moroccan Hanging Lantern|899-2199', 'Edison Bulb String 5 m|599-1499', 'Glass Dome Pendant|1999-4499'],
      specs: { Colour: ['Warm white', 'Multicolour', 'Brass finish'], Power: ['Plug-in', 'USB powered', 'Battery operated'] }, facets: ['Power'],
      blurb: '{name} creates a cosy, festive mood in any room.', bullets: ['Indoor use', 'Includes fittings', 'Easy installation', '7-day easy returns'] },
    { id: 'CUS', category: 'cushions-covers', count: 20, type: 'VARIABLE', brands: ['weavora', 'artisana'], gst: 5, hsn: '6304', price: [249, 1199], ending: 99, weightG: [150, 600], popularity: 2.4, stock: [20, 120], palette: ['9a3412', 'ffedd5'],
      models: ['Velvet Cushion Cover Set of 2|449-899', 'Embroidered Cushion Cover|349-799', 'Cotton Tassel Cushion Cover|299-699', 'Boho Print Cushion Cover Set of 5|699-1199', 'Chenille Cushion Cover|399-799', 'Linen Striped Cushion Cover|349-749', 'Block Print Cushion Cover|299-649', 'Faux Fur Cushion|599-1199', 'Filled Cushion with Cover|699-1199', 'Ikat Cushion Cover Set of 2|499-999'],
      axes: [axis('Size', ['16x16 in', '18x18 in', '20x20 in']), colourAxis(['Mustard', 'Teal', 'Terracotta'])], maxVariants: 4,
      specs: { Fabric: ['Velvet', 'Cotton', 'Linen', 'Chenille'], Style: ['Solid', 'Embroidered', 'Printed'] }, facets: ['Fabric'],
      blurb: '{name} adds texture and colour to your sofa or bed.', bullets: ['Concealed zip closure', 'Machine washable cover', 'Fade-resistant', '7-day easy returns'] },
    { id: 'CRT', category: 'curtains', count: 16, type: 'VARIABLE', brands: ['weavora', 'artisana'], gst: 12, hsn: '6303', price: [599, 3499], ending: 99, weightG: [400, 1800], popularity: 1.6, stock: [15, 90], palette: ['155e75', 'cffafe'],
      models: ['Blackout Door Curtain Pair|899-1999', 'Sheer Window Curtain Pair|599-1299', 'Cotton Linen Curtain Pair|999-2299', 'Printed Door Curtain Pair|799-1799', 'Velvet Window Curtain Pair|1499-3499', 'Eyelet Curtain Pair|899-1999', 'Tassel Border Curtain Pair|1099-2399', 'Embroidered Curtain Pair|1399-2999'],
      axes: [axis('Length', ['5 ft', '7 ft', '9 ft']), colourAxis(['Beige', 'Grey', 'Navy'])], maxVariants: 4,
      specs: { Fabric: ['Polyester', 'Cotton linen', 'Velvet'], Light: ['Blackout', 'Light filtering', 'Sheer'] }, facets: ['Light'],
      blurb: '{name} frames your windows and controls light beautifully.', bullets: ['Rod pocket or eyelet', 'Machine washable', 'Fade-resistant', '7-day easy returns'] },
    { id: 'RUG', category: 'rugs-carpets', count: 12, type: 'VARIABLE', brands: ['weavora', 'artisana'], gst: 12, hsn: '5702', price: [799, 12999], ending: 99, weightG: [1200, 9000], popularity: 1.0, stock: [6, 40], palette: ['57534e', 'f5f5f4'],
      models: ['Tufted Cotton Rug|1499-5999', 'Handwoven Dhurrie|1999-6999', 'Shaggy Rug|1299-5999', 'Jute Round Rug|1999-5999', 'Geometric Print Carpet|1799-7999', 'Anti-Skid Door Mat Set|799-1599'],
      axes: [axis('Size', ['3x5 ft', '4x6 ft', '5x7 ft'])], maxVariants: 3,
      specs: { Material: ['Cotton', 'Jute', 'Polyester', 'Wool blend'], Pile: ['Flat weave', 'Low pile', 'Shaggy'] }, facets: ['Material'],
      blurb: '{name} anchors the room and feels great underfoot.', bullets: ['Anti-slip backing on select styles', 'Vacuum or spot clean', 'Fade-resistant dyes', '7-day easy returns'] },
    { id: 'VAS', category: 'vases', count: 14, type: 'SIMPLE', brands: ['claycraft', 'hearthstyle'], gst: 12, hsn: '6913', price: [299, 3999], ending: 99, weightG: [350, 3000], popularity: 1.3, stock: [10, 70], palette: ['365314', 'ecfccb'],
      models: ['Ceramic Bud Vase|299-799', 'Fluted Ceramic Vase|699-1799', 'Glass Cylinder Vase Set of 3|599-1499', 'Terracotta Matka Vase|499-1299', 'Metal Brass Vase|999-2499', 'Textured Floor Vase|1999-3999', 'Hand-Painted Blue Pottery Vase|899-2299'],
      specs: { Material: ['Ceramic', 'Glass', 'Terracotta', 'Brass'], Height: ['Small', 'Medium', 'Tall'] }, facets: ['Material'],
      blurb: '{name} shows off fresh or dried flowers with style.', bullets: ['Waterproof interior', 'Stable base', 'Handle with care', '7-day easy returns'] },
    { id: 'PLN', category: 'planters', count: 14, type: 'SIMPLE', brands: ['greenleaf-living', 'claycraft'], gst: 18, hsn: '3926', price: [199, 3499], ending: 99, weightG: [250, 4500], popularity: 1.4, stock: [15, 100], palette: ['14532d', 'dcfce7'],
      models: ['Ceramic Planter with Tray|399-1299', 'Metal Hanging Planter|499-1299', 'Self-Watering Pot|299-899', 'Wooden Plant Stand|799-2199', 'Artificial Money Plant|249-699', 'Artificial Fern in Pot|499-1499', 'Succulent Planter Set of 3|399-999'],
      specs: { Material: ['Ceramic', 'Metal', 'Plastic', 'Wood'], Use: ['Indoor', 'Outdoor', 'Indoor and outdoor'] }, facets: ['Use'],
      blurb: '{name} brings greenery to your home with minimal upkeep.', bullets: ['Drainage hole with tray where listed', 'UV-stabilised on outdoor styles', 'Easy to clean', '7-day easy returns'] },
    { id: 'DIN', category: 'dinnerware', count: 14, type: 'SIMPLE', brands: ['dwellmate', 'claycraft'], gst: 12, hsn: '6911', price: [399, 6999], ending: 99, weightG: [600, 9000], popularity: 1.3, stock: [8, 50], palette: ['1e293b', 'e2e8f0'],
      models: ['Ceramic Dinner Set 24 Pieces|3999-6999', 'Stoneware Dinner Set 18 Pieces|2999-5499', 'Bone China Dinner Set 12 Pieces|4999-6999', 'Soup Bowl Set of 6|599-1499', 'Dessert Plates Set of 6|499-1299', 'Rice Bowl Set of 4|399-999', 'Handmade Platter|799-1999'],
      specs: { Material: ['Ceramic', 'Stoneware', 'Bone china', 'Melamine'], Safety: ['Microwave and dishwasher safe', 'Microwave safe', 'Hand wash only'] }, facets: ['Material'],
      blurb: '{name} makes everyday meals and special dinners look their best.', bullets: ['Chip-resistant glaze', 'Food-safe materials', 'Stackable', '7-day easy returns'] },
    { id: 'DRK', category: 'drinkware-serveware', count: 14, type: 'SIMPLE', brands: ['dwellmate', 'woodnest'], gst: 18, hsn: '7013', price: [199, 3499], ending: 99, weightG: [250, 3500], popularity: 1.4, stock: [15, 90], palette: ['0c4a6e', 'e0f2fe'],
      models: ['Tumbler Glass Set of 6|399-999', 'Coffee Mug Set of 4|449-1199', 'Wooden Serving Tray|599-1599', 'Glass Jar Set with Lids|499-1299', 'Cake Stand|699-1799', 'Bamboo Coaster Set|199-499', 'Copper Water Jug|899-2299'],
      specs: { Material: ['Glass', 'Ceramic', 'Wood', 'Copper'], Pack: ['Set of 4', 'Set of 6', 'Single'] }, facets: ['Material'],
      blurb: '{name} makes serving and sipping a pleasure.', bullets: ['Food-safe', 'Gift-ready packaging', 'Easy to clean', '7-day easy returns'] },
    { id: 'CND', category: 'candles-fragrance', count: 16, type: 'SIMPLE', brands: ['scentora', 'artisana'], gst: 12, hsn: '3406', price: [149, 1999], ending: 99, weightG: [100, 800], popularity: 2.0, stock: [20, 140], palette: ['701a75', 'fae8ff'],
      models: ['Soy Wax Scented Candle Jar|349-899', 'Tealight Candles Pack of 50|199-499', 'Reed Diffuser Set|599-1499', 'Incense Sticks Combo|149-399', 'Aroma Oil Burner Set|499-1299', 'Pillar Candle Set of 3|299-799', 'Floating Candles Set|249-599', 'Gift Candle Trio|799-1999'],
      specs: { Fragrance: ['Lavender', 'Sandalwood', 'Vanilla', 'Jasmine', 'Ocean breeze'], BurnTime: ['25 hours', '40 hours', '60 hours'] }, facets: ['Fragrance'],
      blurb: '{name} fills your home with a calming, long-lasting fragrance.', bullets: ['Clean-burning wax', 'Cotton wick', 'Never leave a burning candle unattended', '7-day easy returns'] },
    { id: 'SHW', category: 'showpieces', count: 18, type: 'SIMPLE', brands: ['hearthstyle', 'woodnest'], gst: 18, hsn: '4420', price: [299, 5999], ending: 99, weightG: [150, 4000], popularity: 1.5, stock: [8, 60], palette: ['3f3f46', 'fafafa'],
      models: ['Brass Elephant Pair|999-2499', 'Ceramic Owl Showpiece|399-999', 'Wooden Key Holder|449-1199', 'Bookends Pair|699-1799', 'Photo Frame Collage Set|599-1599', 'Tabletop Fountain|1499-3999', 'Decorative Bowl|499-1499', 'Floating Wall Shelves Set of 3|899-2299', 'Wooden Tray Organiser|599-1499'],
      specs: { Material: ['Brass', 'Ceramic', 'Wood', 'Resin'], Finish: ['Matte', 'Antique', 'Glossy'] }, facets: ['Material'],
      blurb: '{name} adds a finishing touch to shelves, consoles and tables.', bullets: ['Felt base to protect surfaces', 'Handcrafted detail', 'Dust with a soft cloth', '7-day easy returns'] },
  ],
  coupons: standardCoupons('DN', { bigOrderRupees: 2499, freeShipMin: 1299 }),
  banners: [
    { title: 'Festive Home Makeover', subtitle: 'Lights, cushions and candles for the season', cta: 'Shop now', link: '/products' },
    { title: 'Soft Furnishings Sale', subtitle: 'Curtains, rugs and cushion covers up to 40% off', cta: 'Shop soft furnishings', link: '/products?category=soft-furnishings' },
    { title: 'Light Up Your Space', subtitle: 'Lamps and pendants from Rs 249', cta: 'Explore lighting', link: '/products?category=lighting' },
  ],
};
