import type { TenantSpec } from '../types';
import { axis, colourAxis, STAFF_TEMPLATE, standardCoupons } from './common';

/** ElectroHub India: consumer electronics. All brand names are fictional. */
export const ELECTROHUB: TenantSpec = {
  slug: 'electrohub-india',
  tag: 'EHI',
  businessName: 'ElectroHub India',
  legalName: 'ElectroHub India Private Limited',
  gstin: '27EHIND0001A1Z5',
  storefrontTheme: 'circuit',
  themeTemplate: 'electronics',
  brandColor: '1d4ed8',
  accentColor: '0ea5e9',
  tagline: 'Smart tech, honest prices, delivered across India',
  storeName: 'ElectroHub India',
  contactPhone: '+917000011001',
  supportPhone: '+917000011002',
  reviewNoun: 'device',
  homeStateShare: 0.3,
  weekendBoost: 1.2,
  freeShippingRupees: 999,
  shippingRupees: 99,
  paymentMix: [['CARD', 34], ['UPI', 28], ['EMI', 16], ['NETBANKING', 8], ['COD', 14]],
  lineMix: [[1, 62], [2, 26], [3, 9], [4, 3]],
  qtyMix: [[1, 93], [2, 6], [3, 1]],
  staff: STAFF_TEMPLATE([['Rohit', 'Bhandari'], ['Sunita', 'Kamath'], ['Abhay', 'Naik'], ['Girish', 'Salvi'], ['Tanuja', 'Pawar'], ['Kabir', 'Dhawan']]),
  warehouses: [
    { code: 'WH-MUM-01', name: 'Bhiwandi Fulfilment Centre', line1: 'Gala 14, Logistics Park, Kalher', city: 'Thane', state: 'Maharashtra', stateCode: 'MH', postal: '421302', lat: '19.2969000', lng: '73.0630000' },
    { code: 'WH-BLR-01', name: 'Bengaluru Hub', line1: 'Plot 22, Peenya Industrial Area', city: 'Bengaluru', state: 'Karnataka', stateCode: 'KA', postal: '560058', lat: '13.0285000', lng: '77.5197000' },
  ],
  brands: [
    { slug: 'voltix', name: 'Voltix', description: 'Value-packed 5G smartphones and feature phones.' },
    { slug: 'nexora', name: 'Nexora', description: 'Phones, laptops and TVs engineered for everyday performance.' },
    { slug: 'zenbyte', name: 'Zenbyte', description: 'Laptops and computing accessories for students and professionals.' },
    { slug: 'auralis', name: 'Auralis', description: 'Headphones and earbuds tuned for clear sound.' },
    { slug: 'orbito', name: 'Orbito', description: 'Portable speakers and soundbars.' },
    { slug: 'pixelon', name: 'Pixelon', description: 'Smart televisions with sharp displays.' },
    { slug: 'kinetiq', name: 'Kinetiq', description: 'Smartwatches and fitness bands.' },
    { slug: 'lumora', name: 'Lumora', description: 'Everyday accessories for phones and desks.' },
    { slug: 'gridwell', name: 'Gridwell', description: 'Chargers, cables and power banks you can rely on.' },
    { slug: 'sparkline', name: 'Sparkline', description: 'High-capacity power banks.' },
    { slug: 'aeroflux', name: 'Aeroflux', description: 'Fans, heaters and home appliances.' },
    { slug: 'brewmate', name: 'Brewmate', description: 'Kitchen appliances that save time.' },
  ],
  categories: [
    { slug: 'smartphones', name: 'Smartphones', description: 'Latest 5G smartphones and reliable feature phones.', children: [
      { slug: 'smartphones-5g', name: '5G Smartphones', description: 'Fast 5G phones across every budget.' },
      { slug: 'feature-phones', name: 'Feature Phones', description: 'Simple, durable phones with long battery life.' },
    ] },
    { slug: 'laptops-computers', name: 'Laptops & Computers', description: 'Laptops and accessories for work, study and play.', children: [
      { slug: 'laptops', name: 'Laptops', description: 'Thin-and-light, student, business and gaming laptops.' },
      { slug: 'computer-accessories', name: 'Computer Accessories', description: 'Mice, keyboards, storage and more.' },
    ] },
    { slug: 'audio', name: 'Audio', description: 'Headphones, earbuds and speakers.', children: [
      { slug: 'earbuds', name: 'Earbuds', description: 'True wireless earbuds.' },
      { slug: 'headphones', name: 'Headphones', description: 'Over-ear and on-ear headphones.' },
      { slug: 'speakers', name: 'Speakers & Soundbars', description: 'Bluetooth speakers and soundbars.' },
    ] },
    { slug: 'televisions', name: 'Televisions', description: 'Smart TVs in every size.', children: [
      { slug: 'smart-tvs', name: 'Smart TVs', description: '4K and QLED smart televisions.' },
    ] },
    { slug: 'wearables', name: 'Wearables', description: 'Smartwatches and fitness trackers.', children: [
      { slug: 'smartwatches', name: 'Smartwatches & Bands', description: 'Track health, fitness and notifications.' },
    ] },
    { slug: 'mobile-accessories', name: 'Mobile Accessories', description: 'Chargers, cables, power banks and cases.', children: [
      { slug: 'chargers-cables', name: 'Chargers & Cables', description: 'Fast chargers and durable cables.' },
      { slug: 'power-banks', name: 'Power Banks', description: 'Stay powered on the move.' },
      { slug: 'cases-covers', name: 'Cases & Protection', description: 'Back covers and screen guards.' },
    ] },
    { slug: 'small-appliances', name: 'Small Appliances', description: 'Kitchen and home appliances.', children: [
      { slug: 'kitchen-appliances', name: 'Kitchen Appliances', description: 'Mixers, kettles, air fryers and more.' },
      { slug: 'home-appliances', name: 'Home Appliances', description: 'Fans, irons, heaters and vacuum cleaners.' },
    ] },
  ],
  families: [
    { id: 'SMP', category: 'smartphones-5g', count: 24, type: 'VARIABLE', brands: ['voltix', 'nexora'], gst: 18, hsn: '8517', price: [8999, 69999], ending: 99, weightG: [165, 215], dimsMm: [160, 75, 8], popularity: 3.2, stock: [30, 140], palette: ['0f172a', '38bdf8'],
      models: ['Nova 5G', 'Nova Pro 5G', 'Edge 5G', 'Edge Lite 5G', 'Spark 5G', 'Spark Plus 5G', 'Orbit 5G', 'Zen X 5G', 'Pulse 5G', 'Prime 5G', 'Vista 5G', 'Aero 5G'],
      axes: [axis('Storage', [['128GB', 0], ['256GB', 3000], ['512GB', 8000]]), colourAxis(['Midnight Black', 'Ocean Blue', 'Pearl White'])], maxVariants: 5,
      specs: { Display: ['6.5" FHD+ AMOLED 120Hz', '6.7" FHD+ AMOLED 120Hz', '6.4" FHD+ LCD 90Hz'], Battery: ['5000 mAh with 33W charging', '5000 mAh with 67W charging', '4500 mAh with 45W charging'], Processor: ['Octa-core 5G chipset', 'Octa-core 4nm 5G chipset'], Camera: ['50MP + 8MP dual rear', '64MP + 8MP + 2MP triple rear', '108MP + 12MP dual rear'] }, facets: ['Display', 'Battery'],
      blurb: '{name} is a 5G smartphone with a bright high-refresh display, an all-day battery and a capable camera system.', bullets: ['5G dual-SIM with VoLTE', 'Fast charger included in the box', 'In-display fingerprint sensor', '1 year manufacturer warranty on the device, 6 months on accessories'] },
    { id: 'FPH', category: 'feature-phones', count: 4, type: 'SIMPLE', brands: ['voltix'], gst: 12, hsn: '8517', price: [1299, 2999], ending: 99, weightG: [85, 140], popularity: 0.6, stock: [40, 160], palette: ['111827', 'a3e635'],
      models: ['Classic 105', 'Classic 110', 'Rugged 4G', 'Senior Easy'],
      specs: { Display: ['2.4" colour', '1.8" colour'], Battery: ['1500 mAh removable', '1800 mAh removable'], Network: ['Dual-SIM 4G VoLTE', 'Dual-SIM 2G'] }, facets: ['Network'],
      blurb: '{name} is a dependable feature phone with a long-lasting battery, loud speaker and a built-in torch.', bullets: ['Dual SIM with memory card slot', 'Up to 20 days standby', 'FM radio and torch', '1 year warranty'] },
    { id: 'LAP', category: 'laptops', count: 18, type: 'VARIABLE', brands: ['nexora', 'zenbyte'], gst: 18, hsn: '8471', price: [28999, 119999], ending: 99, weightG: [1300, 2400], dimsMm: [360, 245, 20], popularity: 1.6, stock: [10, 55], palette: ['111827', 'f59e0b'],
      models: ['Slate 14', 'Slate 15', 'Book Air 13', 'Book Pro 14', 'Studio 16', 'Gamer X 15', 'Gamer X Pro 17', 'Student Lite 14', 'Business 15'],
      axes: [axis('Memory', [['8GB / 256GB SSD', 0], ['16GB / 512GB SSD', 9000], ['16GB / 1TB SSD', 16000]])], maxVariants: 3,
      specs: { Processor: ['Octa-core 12th Gen class', 'Hexa-core mobile processor', '10-core performance processor'], Display: ['14" FHD IPS', '15.6" FHD IPS 144Hz', '16" QHD+ 120Hz'], OS: ['Windows 11 Home', 'Windows 11 Pro', 'No OS (FreeDOS)'] }, facets: ['Processor', 'OS'],
      blurb: '{name} balances performance and portability, with a bright display, a comfortable keyboard and all-day battery life.', bullets: ['Backlit keyboard', 'Wi-Fi 6 and Bluetooth 5.2', 'USB-C charging', '1 year on-site warranty'] },
    { id: 'CAC', category: 'computer-accessories', count: 14, type: 'SIMPLE', brands: ['lumora', 'gridwell', 'zenbyte'], gst: 18, hsn: '8471', price: [349, 9999], ending: 99, weightG: [90, 900], popularity: 1.4, stock: [40, 220], palette: ['1e293b', '22d3ee'],
      models: ['Wireless Mouse M1|349-799', 'Silent Click Mouse|449-999', 'Mechanical Keyboard K87|1999-4499', 'Slim Keyboard and Mouse Combo|899-1799', 'Full HD Webcam|1299-2999', 'USB-C Hub 7-in-1|1499-3299', 'Aluminium Laptop Stand|799-1799', 'Laptop Cooling Pad|899-1999', '1TB Portable SSD|6499-8999', '2TB Portable HDD|4999-6999', 'Wireless Presenter|699-1499', '4-Port USB 3.0 Hub|399-899', 'Gaming Mouse Pad XL|299-799', 'Laptop Sleeve 15.6 inch|499-1299'],
      specs: { Connectivity: ['2.4 GHz wireless', 'Bluetooth 5.0', 'USB-C', 'USB-A'], Warranty: ['1 year', '2 years', '6 months'] }, facets: ['Connectivity'],
      blurb: '{name} is a practical desk upgrade built for daily use.', bullets: ['Plug-and-play setup', 'Compact and portable', 'Tested for durability', 'Brand warranty included'] },
    { id: 'EAR', category: 'earbuds', count: 14, type: 'VARIABLE', brands: ['auralis', 'orbito', 'kinetiq'], gst: 18, hsn: '8518', price: [799, 7999], ending: 99, weightG: [40, 90], popularity: 2.6, stock: [60, 260], palette: ['0b1120', 'a78bfa'],
      models: ['Buds Air 2', 'Buds Air Pro', 'Buds Sport', 'Buds Lite', 'Buds ANC 3', 'Neo Buds', 'Beat Buds'],
      axes: [colourAxis(['Black', 'White', 'Blue'])], maxVariants: 3,
      specs: { Playtime: ['Up to 24 hours with case', 'Up to 36 hours with case', 'Up to 48 hours with case'], Features: ['Active noise cancellation', 'Low-latency gaming mode', 'IPX5 sweat resistance', 'Dual-mic call clarity'] }, facets: ['Features'],
      blurb: '{name} true wireless earbuds deliver punchy sound with a pocketable charging case.', bullets: ['Bluetooth 5.3', 'Touch controls', 'Type-C fast charging', '1 year warranty'] },
    { id: 'HPN', category: 'headphones', count: 10, type: 'SIMPLE', brands: ['auralis', 'orbito'], gst: 18, hsn: '8518', price: [999, 12999], ending: 99, weightG: [180, 320], popularity: 1.2, stock: [25, 120], palette: ['18181b', 'fb7185'],
      models: ['Studio Over-Ear', 'Bass Boost On-Ear', 'Pro ANC Over-Ear', 'Gamer Headset 7.1', 'Travel Foldable'],
      specs: { Type: ['Over-ear wireless', 'On-ear wireless', 'Over-ear wired'], Battery: ['Up to 40 hours', 'Up to 60 hours', 'Wired (no battery)'] }, facets: ['Type'],
      blurb: '{name} headphones are comfortable for long sessions and tuned for balanced, detailed sound.', bullets: ['Soft memory-foam ear cushions', 'Built-in mic', 'Foldable design', '1 year warranty'] },
    { id: 'SPK', category: 'speakers', count: 10, type: 'SIMPLE', brands: ['orbito', 'auralis'], gst: 18, hsn: '8518', price: [999, 24999], ending: 99, weightG: [350, 4200], popularity: 1.1, stock: [20, 100], palette: ['172554', 'f472b6'],
      models: ['Boom Mini Bluetooth Speaker|999-2499', 'Boom Max Party Speaker|6999-14999', 'Soundbar 2.1 120W|5999-9999', 'Soundbar 5.1 Home Theatre|12999-24999', 'Desk Stereo Speakers|1499-3499'],
      specs: { Output: ['10W', '20W', '120W', '300W'], Connectivity: ['Bluetooth 5.2', 'Bluetooth + HDMI ARC', 'Bluetooth + AUX'] }, facets: ['Connectivity'],
      blurb: '{name} fills the room with clear highs and deep bass.', bullets: ['Wireless streaming', 'Rechargeable battery on portable models', 'Splash resistant', '1 year warranty'] },
    { id: 'TVS', category: 'smart-tvs', count: 12, type: 'VARIABLE', brands: ['pixelon', 'nexora'], gst: 28, hsn: '8528', price: [11999, 54999], ending: 99, weightG: [4500, 22000], popularity: 1.0, stock: [6, 40], palette: ['020617', '60a5fa'],
      models: ['Vision 4K', 'Vision QLED', 'Cinema HD', 'Crystal 4K', 'Ultra Bright 4K', 'Frame UHD'],
      axes: [axis('Screen size', [['32 inch', 0], ['43 inch', 9000], ['50 inch', 17000], ['55 inch', 24000]])], maxVariants: 3,
      specs: { Resolution: ['HD Ready', 'Full HD', '4K Ultra HD'], Platform: ['Google TV', 'Android TV', 'Linux smart OS'], Sound: ['20W stereo', '30W Dolby Audio'] }, facets: ['Resolution', 'Platform'],
      blurb: '{name} brings your favourite shows, sports and games to life with a sharp, vibrant panel.', bullets: ['Built-in Wi-Fi and Chromecast', 'HDMI ARC and 2 USB ports', 'Voice remote', '1 year comprehensive warranty plus 1 year on panel'] },
    { id: 'SMW', category: 'smartwatches', count: 16, type: 'VARIABLE', brands: ['kinetiq', 'voltix', 'nexora'], gst: 18, hsn: '8517', price: [1499, 14999], ending: 99, weightG: [30, 75], popularity: 2.0, stock: [30, 170], palette: ['0c0a09', '34d399'],
      models: ['Fit Pro', 'Fit Lite', 'Active AMOLED', 'Active Call', 'Sport 2', 'Trail Rugged'],
      axes: [axis('Strap', ['Black', 'Navy', 'Olive'])], maxVariants: 3,
      specs: { Display: ['1.43" AMOLED', '1.69" LCD', '1.96" AMOLED'], Battery: ['Up to 7 days', 'Up to 10 days', 'Up to 14 days'], Features: ['Bluetooth calling', 'SpO2 and heart-rate', 'Built-in GPS', '100+ sports modes'] }, facets: ['Features'],
      blurb: '{name} tracks your workouts and sleep and keeps notifications on your wrist.', bullets: ['IP68 water resistance', 'Magnetic fast charger', 'Works with Android and iOS', '1 year warranty'] },
    { id: 'CHG', category: 'chargers-cables', count: 18, type: 'SIMPLE', brands: ['gridwell', 'lumora'], gst: 18, hsn: '8504', price: [199, 3499], ending: 99, weightG: [40, 260], popularity: 2.2, stock: [80, 400], palette: ['0f172a', 'fde047'],
      models: ['20W USB-C Fast Charger|499-1299', '33W Dual Port Charger|699-1499', '65W GaN Laptop Charger|1999-3499', 'USB-C to USB-C Cable 1m|249-599', 'USB-C Braided Cable 2m|299-699', 'Micro-USB Cable 1m|149-349', 'Car Charger 30W|399-999', 'Wireless Charging Pad 15W|899-1999', '120W GaN Charger 3-Port|2999-4499', '3-in-1 Charging Cable|349-799', '45W Fast Charger|799-1699', 'USB-C Magnetic Cable|449-999'],
      specs: { Output: ['20W', '30W', '33W', '45W', '65W'], Length: ['1 m', '1.5 m', '2 m'] }, facets: ['Output'],
      blurb: '{name} charges quickly and safely, with built-in over-current and over-heat protection.', bullets: ['BIS-certified build', 'Safe for all compatible devices', 'Tangle-free design', '6 months warranty'] },
    { id: 'PWB', category: 'power-banks', count: 12, type: 'SIMPLE', brands: ['sparkline', 'gridwell'], gst: 28, hsn: '8507', price: [799, 3999], ending: 99, weightG: [210, 520], popularity: 1.8, stock: [40, 200], palette: ['1c1917', 'f97316'],
      models: ['10000mAh Slim Power Bank|899-1599', '20000mAh Fast Charge Power Bank|1499-2499', '20000mAh PD 45W Power Bank|2299-3499', '30000mAh Power Bank|2499-3999', '5000mAh Pocket Power Bank|599-999', '10000mAh Magnetic Wireless Power Bank|1799-2799'],
      specs: { Capacity: ['5000 mAh', '10000 mAh', '20000 mAh', '30000 mAh'], Output: ['18W', '22.5W', '45W PD'] }, facets: ['Capacity'],
      blurb: '{name} keeps your phone, earbuds and tablet topped up through the day.', bullets: ['Dual USB output plus USB-C', 'LED charge indicator', 'Multi-layer safety protection', '1 year warranty'] },
    { id: 'CSE', category: 'cases-covers', count: 14, type: 'VARIABLE', brands: ['lumora', 'gridwell'], gst: 18, hsn: '3926', price: [199, 999], ending: 99, weightG: [25, 70], popularity: 1.3, stock: [60, 300], palette: ['27272a', '2dd4bf'],
      models: ['Shockproof Back Cover|249-599', 'Clear Armor Case|199-499', 'Matte Silicon Case|199-449', 'Tempered Glass Guard 2-Pack|199-399', 'Flip Wallet Case|399-799', 'Rugged Bumper Case|449-899', 'Privacy Screen Guard|299-599'],
      axes: [colourAxis(['Black', 'Blue', 'Clear'])], maxVariants: 3,
      specs: { Material: ['TPU', 'Polycarbonate', 'Tempered glass', 'Faux leather'] }, facets: ['Material'],
      blurb: '{name} protects your phone from drops and scratches without adding bulk.', bullets: ['Precise cut-outs', 'Raised edges for camera and screen', 'Easy to install', '3 months replacement warranty'] },
    { id: 'KIT', category: 'kitchen-appliances', count: 16, type: 'SIMPLE', brands: ['brewmate', 'aeroflux'], gst: 18, hsn: '8509', price: [599, 9999], ending: 99, weightG: [900, 6500], popularity: 1.5, stock: [15, 90], palette: ['431407', 'fdba74'],
      models: ['Mixer Grinder 750W|2499-3999', 'Mixer Grinder 1000W 3 Jar|3299-5499', 'Air Fryer 4L|4499-6999', 'Air Fryer 6L Digital|5999-9999', 'Electric Kettle 1.5L|699-1499', 'Induction Cooktop 2000W|1799-3299', 'Pop-up Toaster 2-Slice|1199-2199', 'Rice Cooker 1.8L|1499-2799', 'Sandwich Maker|899-1699', 'Hand Blender 400W|799-1599', 'Cold-Press Juicer|3999-7499', 'Electric Chopper|599-1299'],
      specs: { Power: ['400W', '750W', '1000W', '1500W', '2000W'], Warranty: ['1 year', '2 years'] }, facets: ['Power'],
      blurb: '{name} makes daily cooking quicker and cleaner.', bullets: ['ISI-marked electricals', 'Easy-clean parts', 'Overload protection', 'Service available across India'] },
    { id: 'HOM', category: 'home-appliances', count: 18, type: 'SIMPLE', brands: ['aeroflux', 'brewmate'], gst: 18, hsn: '8516', price: [699, 12999], ending: 99, weightG: [800, 9000], popularity: 1.2, stock: [12, 80], palette: ['422006', 'fcd34d'],
      models: ['Ceiling Fan 1200mm|1799-2999', 'BLDC Ceiling Fan|3299-4999', 'Table Fan 400mm|1499-2499', 'Pedestal Fan|1999-3499', 'Room Heater 2000W|1499-2999', 'Steam Iron 1400W|899-1799', 'Dry Iron|499-999', 'Bagless Vacuum Cleaner|4999-9999', 'Handheld Vacuum Cleaner|2499-4499', 'Hair Dryer 1600W|699-1599', 'Garment Steamer|1999-3499', 'Room Air Purifier|6999-12999', 'Geyser 15L|5999-8999', 'Water Heater Instant 3L|2999-4999'],
      specs: { Power: ['45W', '1400W', '1600W', '2000W'], Warranty: ['1 year', '2 years', '5 years on motor'] }, facets: ['Warranty'],
      blurb: '{name} is built for dependable everyday use around the home.', bullets: ['Energy-efficient design', 'Safety cut-off', 'Pan-India service network', 'Warranty as listed'] },
  ],
  coupons: standardCoupons('EH', { bigOrderRupees: 4999, freeShipMin: 499 }),
  banners: [
    { title: 'Festive Tech Sale', subtitle: 'Up to 40% off on smartphones, laptops and audio', cta: 'Shop the sale', link: '/products' },
    { title: 'Upgrade your sound', subtitle: 'Earbuds, headphones and speakers from Rs 799', cta: 'Explore audio', link: '/products?category=audio' },
    { title: 'Zero-cost EMI', subtitle: 'On select smartphones and televisions', cta: 'View offers', link: '/products?category=smartphones' },
  ],
};
