import type { TenantSpec } from '../types';
import { packAxis, STAFF_TEMPLATE, standardCoupons } from './common';

const PACK_KG = packAxis([['1 kg', 1], ['5 kg', 4.7], ['10 kg', 9]]);
const PACK_SMALL = packAxis([['500 g', 1], ['1 kg', 1.9], ['2 kg', 3.6]]);
const PACK_SPICE = packAxis([['100 g', 1], ['200 g', 1.85]]);
const PACK_OIL = packAxis([['1 L', 1], ['5 L', 4.6]]);
const PACK_TEA = packAxis([['250 g', 1], ['500 g', 1.9]]);

/** FreshBasket Grocery: staples, dairy, produce, snacks, beverages, packaged foods. Fictional brands. */
export const FRESHBASKET: TenantSpec = {
  slug: 'freshbasket-grocery',
  tag: 'FBG',
  businessName: 'FreshBasket Grocery',
  legalName: 'FreshBasket Foods Private Limited',
  gstin: '29FRESH0003C1Z9',
  storefrontTheme: 'harvest',
  themeTemplate: 'grocery',
  brandColor: '15803d',
  accentColor: 'f59e0b',
  tagline: 'Fresh groceries at your doorstep',
  storeName: 'FreshBasket Grocery',
  contactPhone: '+917000033001',
  supportPhone: '+917000033002',
  reviewNoun: 'pack',
  homeStateShare: 0.55,
  weekendBoost: 1.45,
  freeShippingRupees: 499,
  shippingRupees: 39,
  paymentMix: [['COD', 38], ['UPI', 44], ['CARD', 10], ['WALLET', 8]],
  lineMix: [[2, 24], [3, 28], [4, 24], [5, 16], [1, 8]],
  qtyMix: [[1, 62], [2, 28], [3, 8], [4, 2]],
  staff: STAFF_TEMPLATE([['Lakshmi', 'Narayanan'], ['Prakash', 'Hegde'], ['Meenakshi', 'Rao'], ['Basavaraj', 'Patil'], ['Sowmya', 'Gowda'], ['Naveen', 'Shetty']]),
  warehouses: [
    { code: 'WH-BLR-01', name: 'Bengaluru Dark Store Hub', line1: 'No. 8, Whitefield Warehouse Complex', city: 'Bengaluru', state: 'Karnataka', stateCode: 'KA', postal: '560066', lat: '12.9698000', lng: '77.7500000' },
    { code: 'WH-HYD-01', name: 'Hyderabad Fulfilment Centre', line1: 'Plot 17, Medchal Logistics Park', city: 'Hyderabad', state: 'Telangana', stateCode: 'TS', postal: '500067', lat: '17.5400000', lng: '78.4800000' },
  ],
  brands: [
    { slug: 'goldfield-mills', name: 'Goldfield Mills', description: 'Flours and grains milled fresh.' },
    { slug: 'dhanya-naturals', name: 'Dhanya Naturals', description: 'Pulses, rice and staples sourced from farms.' },
    { slug: 'kisan-valley', name: 'Kisan Valley', description: 'Farm-fresh fruits and vegetables.' },
    { slug: 'spiceroute', name: 'Spiceroute', description: 'Whole and ground spices with true aroma.' },
    { slug: 'pureflow-dairy', name: 'Pureflow Dairy', description: 'Milk, curd, paneer and ghee.' },
    { slug: 'greenpatch', name: 'Greenpatch', description: 'Cold-pressed oils and healthy pantry basics.' },
    { slug: 'crunchbox', name: 'Crunchbox', description: 'Biscuits, namkeen and munchies.' },
    { slug: 'sipwell', name: 'Sipwell', description: 'Tea, coffee and refreshing drinks.' },
    { slug: 'tastekraft', name: 'Tastekraft', description: 'Sauces, spreads and ready-to-cook.' },
    { slug: 'nutrimeal', name: 'Nutrimeal', description: 'Cereals, oats and breakfast foods.' },
    { slug: 'bakehouse-daily', name: 'Bakehouse Daily', description: 'Bread, buns and bakery essentials.' },
    { slug: 'homeglow', name: 'Homeglow', description: 'Cleaning and personal care essentials.' },
  ],
  categories: [
    { slug: 'staples', name: 'Staples', description: 'Atta, rice, dals, oils and masalas for the daily kitchen.', children: [
      { slug: 'atta-flours', name: 'Atta & Flours', description: 'Wheat atta, besan and millet flours.' },
      { slug: 'rice-grains', name: 'Rice & Grains', description: 'Basmati, sona masoori and more.' },
      { slug: 'dals-pulses', name: 'Dals & Pulses', description: 'Toor, moong, chana and other pulses.' },
      { slug: 'edible-oils', name: 'Edible Oils', description: 'Sunflower, groundnut, mustard and more.' },
      { slug: 'spices-masalas', name: 'Spices & Masalas', description: 'Whole spices, powders, salt and sugar.' },
    ] },
    { slug: 'dairy-eggs', name: 'Dairy & Eggs', description: 'Milk, curd, paneer, butter, eggs and bread.', children: [
      { slug: 'dairy-essentials', name: 'Dairy Essentials', description: 'Milk, curd, paneer, butter and cheese.' },
      { slug: 'eggs-bread', name: 'Eggs & Bread', description: 'Farm eggs and fresh bakery bread.' },
    ] },
    { slug: 'fruits-vegetables', name: 'Fruits & Vegetables', description: 'Fresh, seasonal produce.', children: [
      { slug: 'fresh-fruits', name: 'Fresh Fruits', description: 'Seasonal fruits sold by weight.' },
      { slug: 'fresh-vegetables', name: 'Fresh Vegetables', description: 'Everyday vegetables and herbs.' },
    ] },
    { slug: 'snacks', name: 'Snacks & Biscuits', description: 'Biscuits, namkeen and munchies.', children: [
      { slug: 'biscuits-cookies', name: 'Biscuits & Cookies', description: 'Tea-time biscuits and cookies.' },
      { slug: 'namkeen-chips', name: 'Namkeen & Chips', description: 'Chips, bhujia and roasted snacks.' },
    ] },
    { slug: 'beverages', name: 'Beverages', description: 'Tea, coffee, juices and soft drinks.', children: [
      { slug: 'tea-coffee', name: 'Tea & Coffee', description: 'Tea leaves, green tea and coffee.' },
      { slug: 'juices-drinks', name: 'Juices & Soft Drinks', description: 'Juices, coconut water and soft drinks.' },
    ] },
    { slug: 'packaged-foods', name: 'Packaged Foods', description: 'Cereals, sauces, noodles and ready-to-cook.', children: [
      { slug: 'breakfast-cereals', name: 'Breakfast & Cereals', description: 'Oats, corn flakes and muesli.' },
      { slug: 'sauces-spreads', name: 'Sauces & Spreads', description: 'Ketchup, jams, pickles and spreads.' },
      { slug: 'noodles-pasta', name: 'Noodles & Pasta', description: 'Instant noodles, pasta and soups.' },
    ] },
    { slug: 'household', name: 'Household & Care', description: 'Cleaning and personal care.', children: [
      { slug: 'cleaning-supplies', name: 'Cleaning Supplies', description: 'Detergents, dishwash and floor cleaners.' },
      { slug: 'personal-care', name: 'Personal Care', description: 'Soap, shampoo, toothpaste and more.' },
    ] },
  ],
  families: [
    { id: 'ATA', category: 'atta-flours', count: 12, type: 'VARIABLE', brands: ['goldfield-mills', 'dhanya-naturals'], gst: 5, hsn: '1101', price: [55, 140], ending: 9, weightG: [900, 1100], popularity: 3.0, stock: [60, 300], palette: ['854d0e', 'fef3c7'],
      models: ['Whole Wheat Atta|55-95', 'Multigrain Atta|79-140', 'Sharbati Atta|65-115', 'Besan (Gram Flour)|85-140', 'Maida|42-75', 'Rava (Sooji)|48-85', 'Ragi Flour|79-125', 'Jowar Flour|65-105', 'Rice Flour|55-95', 'Bajra Flour|59-99', 'Idli Rava|52-89', 'Corn Flour|58-99'],
      axes: [PACK_KG], maxVariants: 3,
      specs: { Type: ['Stone-ground', 'Chakki fresh', 'Roller milled'], Shelf: ['Best before 6 months', 'Best before 4 months'] }, facets: ['Type'],
      blurb: '{name} is milled fresh and packed hygienically for soft rotis and reliable baking.', bullets: ['No added preservatives', 'Hygienically packed', 'Store in a cool, dry place', 'FSSAI licensed'] },
    { id: 'RIC', category: 'rice-grains', count: 12, type: 'VARIABLE', brands: ['dhanya-naturals', 'goldfield-mills'], gst: 5, hsn: '1006', price: [58, 210], ending: 9, weightG: [900, 1100], popularity: 2.6, stock: [60, 260], palette: ['365314', 'ecfccb'],
      models: ['Basmati Rice Premium|139-210', 'Basmati Rice Everyday|99-149', 'Sona Masoori Rice|68-110', 'Parboiled Rice|62-95', 'Brown Rice|88-140', 'Idli Rice|58-89', 'Poha Thick|52-85', 'Poha Thin|54-88', 'Red Rice (Matta)|95-150', 'Broken Basmati|75-110', 'Black Rice|180-260', 'Murmura (Puffed Rice)|48-78'],
      axes: [PACK_KG], maxVariants: 3,
      specs: { Grain: ['Extra long', 'Medium grain', 'Short grain'], Aged: ['Aged 12 months', 'Aged 24 months', 'Freshly milled'] }, facets: ['Grain'],
      blurb: '{name} cooks up fluffy and flavourful, grain after grain.', bullets: ['Sorted and sifted', 'Stone-free', 'Resealable pack on smaller sizes', 'FSSAI licensed'] },
    { id: 'DAL', category: 'dals-pulses', count: 14, type: 'VARIABLE', brands: ['dhanya-naturals', 'kisan-valley'], gst: 5, hsn: '0713', price: [89, 190], ending: 9, weightG: [450, 550], popularity: 2.4, stock: [50, 240], palette: ['78350f', 'fde68a'],
      models: ['Toor Dal|139-190', 'Moong Dal Split|115-165', 'Moong Whole|105-150', 'Chana Dal|89-135', 'Masoor Dal|92-140', 'Urad Dal Split|130-185', 'Urad Whole|125-180', 'Rajma Chitra|115-170', 'Kabuli Chana|118-175', 'Green Peas Dried|79-120', 'Black Chana|82-125', 'Horse Gram|92-135', 'Lobia (Black Eyed Peas)|95-140', 'Matki (Moth Beans)|100-150'],
      axes: [PACK_SMALL], maxVariants: 3,
      specs: { Type: ['Polished', 'Unpolished', 'Organic-grown'], Protein: ['High protein', 'Rich in fibre'] }, facets: ['Type'],
      blurb: '{name} is carefully sorted for even cooking and rich flavour.', bullets: ['Cleaned and graded', 'No artificial polish on unpolished range', 'Sealed for freshness', 'FSSAI licensed'] },
    { id: 'OIL', category: 'edible-oils', count: 10, type: 'VARIABLE', brands: ['greenpatch', 'goldfield-mills'], gst: 5, hsn: '1512', price: [135, 320], ending: 9, weightG: [900, 950], popularity: 1.8, stock: [40, 180], palette: ['a16207', 'fef9c3'],
      models: ['Refined Sunflower Oil|129-190', 'Cold-Pressed Groundnut Oil|229-320', 'Kachi Ghani Mustard Oil|165-235', 'Coconut Oil|199-290', 'Rice Bran Oil|139-205'],
      axes: [PACK_OIL], maxVariants: 2,
      specs: { Process: ['Refined', 'Cold-pressed', 'Kachi ghani'], Pack: ['Pouch', 'Bottle'] }, facets: ['Process'],
      blurb: '{name} is light on the palate and suited for everyday Indian cooking.', bullets: ['Cholesterol-free', 'Hygienically filled', 'No added colour', 'FSSAI licensed'] },
    { id: 'SPC', category: 'spices-masalas', count: 14, type: 'VARIABLE', brands: ['spiceroute', 'tastekraft'], gst: 5, hsn: '0910', price: [35, 190], ending: 9, weightG: [90, 110], popularity: 2.0, stock: [50, 220], palette: ['7c2d12', 'fed7aa'],
      models: ['Turmeric Powder|42-95', 'Red Chilli Powder|55-120', 'Coriander Powder|38-85', 'Garam Masala|65-150', 'Cumin Seeds|65-135', 'Mustard Seeds|28-60', 'Chai Masala|62-130', 'Biryani Masala|55-120', 'Kasuri Methi|35-75', 'Black Pepper Whole|95-190', 'Cardamom Green|180-320', 'Cinnamon Sticks|58-110', 'Chole Masala|52-110', 'Pav Bhaji Masala|52-110'],
      axes: [PACK_SPICE], maxVariants: 2,
      specs: { Form: ['Powder', 'Whole', 'Blend'], Grade: ['Premium', 'Everyday'] }, facets: ['Form'],
      blurb: '{name} brings vibrant colour and authentic aroma to your cooking.', bullets: ['Freshly ground, vacuum sealed', 'No artificial colours', 'Aroma-lock pouch', 'FSSAI licensed'] },
    { id: 'SSJ', category: 'spices-masalas', count: 6, type: 'SIMPLE', brands: ['goldfield-mills', 'spiceroute'], gst: 5, hsn: '1701', price: [24, 120], ending: 9, weightG: [900, 1100], popularity: 1.8, stock: [80, 300], palette: ['f5f5f4', '78716c'],
      models: ['Refined Sugar 1 kg|44-62', 'Iodised Salt 1 kg|22-32', 'Rock Salt 500 g|32-55', 'Jaggery Powder 500 g|55-95', 'Brown Sugar 500 g|60-98', 'Sendha Namak 500 g|52-85'],
      specs: { Type: ['Crystal', 'Powder', 'Lump'] }, facets: [],
      blurb: '{name} is a pantry basic you will reach for every day.', bullets: ['Free-flowing', 'Hygienically packed', 'Store in a dry place', 'FSSAI licensed'] },
    { id: 'DRY', category: 'dairy-essentials', count: 14, type: 'SIMPLE', brands: ['pureflow-dairy'], gst: 5, hsn: '0401', price: [28, 650], ending: 9, weightG: [250, 1050], popularity: 3.4, stock: [40, 200], palette: ['1e3a8a', 'bfdbfe'],
      models: ['Toned Milk 1 L|60-72', 'Full Cream Milk 1 L|68-80', 'Fresh Curd 400 g|42-60', 'Paneer 200 g|82-110', 'Salted Butter 100 g|56-68', 'Cheese Slices 200 g|125-165', 'Cow Ghee 500 ml|320-420', 'Buttermilk 200 ml|18-28', 'Sweet Lassi 200 ml|28-40', 'Greek Yoghurt 100 g|35-55', 'Cheese Spread 200 g|95-130', 'Flavoured Milk 200 ml|30-45', 'Condensed Milk 400 g|110-150', 'Fresh Cream 200 ml|58-82'],
      specs: { Storage: ['Keep refrigerated', 'Store below 10 C'], Shelf: ['Best before 3 days', 'Best before 7 days', 'Best before 90 days'] }, facets: [],
      blurb: '{name} is sourced from trusted dairies and delivered chilled.', bullets: ['Cold-chain delivery', 'No added preservatives', 'Check best-before on pack', 'FSSAI licensed'] },
    { id: 'EGG', category: 'eggs-bread', count: 6, type: 'SIMPLE', brands: ['bakehouse-daily', 'pureflow-dairy'], gst: 0, hsn: '0407', price: [32, 210], ending: 9, weightG: [300, 1800], popularity: 2.6, stock: [40, 160], palette: ['78350f', 'fef3c7'],
      models: ['Farm Fresh Eggs Tray of 12|88-110', 'Brown Eggs Pack of 6|58-78', 'White Bread 400 g|38-50', 'Brown Bread 400 g|42-56', 'Multigrain Bread 400 g|52-68', 'Pav Buns Pack of 8|34-46'],
      specs: { Storage: ['Store in a cool place', 'Consume within 3 days'] }, facets: [],
      blurb: '{name} is fresh every morning.', bullets: ['Packed hygienically', 'Delivered fresh', 'No added preservatives', 'FSSAI licensed'] },
    { id: 'FRU', category: 'fresh-fruits', count: 10, type: 'SIMPLE', brands: ['kisan-valley'], gst: 0, hsn: '0803', price: [35, 320], ending: 9, weightG: [450, 1050], popularity: 2.2, stock: [30, 140], palette: ['9a3412', 'fed7aa'],
      models: ['Robusta Bananas 1 dozen|52-72', 'Shimla Apples 1 kg|140-210', 'Nagpur Oranges 1 kg|75-110', 'Pomegranate 1 kg|130-190', 'Green Grapes 500 g|60-95', 'Alphonso Mangoes 1 kg|220-320', 'Papaya 1 kg|45-70', 'Watermelon 1 piece|60-95', 'Kiwi Pack of 3|75-110', 'Guava 500 g|40-65'],
      specs: { Origin: ['Maharashtra', 'Himachal Pradesh', 'Karnataka', 'Andhra Pradesh'], Grade: ['Handpicked', 'Farm fresh'] }, facets: ['Origin'],
      blurb: '{name} is picked at peak ripeness and delivered fresh.', bullets: ['Quality-checked', 'Naturally ripened', 'Wash before eating', 'Weight may vary by up to 5 percent'] },
    { id: 'VEG', category: 'fresh-vegetables', count: 14, type: 'SIMPLE', brands: ['kisan-valley'], gst: 0, hsn: '0702', price: [18, 120], ending: 9, weightG: [240, 1050], popularity: 3.0, stock: [40, 180], palette: ['14532d', 'bbf7d0'],
      models: ['Tomato Hybrid 1 kg|28-46', 'Onion 1 kg|28-48', 'Potato 1 kg|24-40', 'Spinach 250 g|18-30', 'Carrot 500 g|32-52', 'Cauliflower 1 piece|32-55', 'Cabbage 1 piece|28-45', 'Capsicum Green 250 g|28-48', 'Okra (Bhindi) 500 g|38-62', 'Brinjal 500 g|30-48', 'Bottle Gourd 1 piece|28-45', 'Ginger 250 g|35-60', 'Garlic 250 g|45-85', 'Coriander Bunch|12-25'],
      specs: { Origin: ['Local farms', 'Karnataka', 'Maharashtra'], Grade: ['Farm fresh', 'Graded'] }, facets: ['Origin'],
      blurb: '{name} comes straight from nearby farms to your kitchen.', bullets: ['Sourced daily', 'Quality-checked', 'Wash before use', 'Weight may vary by up to 5 percent'] },
    { id: 'BIS', category: 'biscuits-cookies', count: 12, type: 'SIMPLE', brands: ['crunchbox', 'bakehouse-daily'], gst: 18, hsn: '1905', price: [10, 220], ending: 9, weightG: [60, 600], popularity: 2.0, stock: [60, 260], palette: ['b45309', 'fef3c7'],
      models: ['Digestive Biscuits 400 g|65-95', 'Cream Biscuits 150 g|20-35', 'Marie Biscuits 250 g|28-45', 'Choco Chip Cookies 200 g|55-90', 'Butter Cookies 300 g|95-155', 'Rusk 500 g|58-90', 'Glucose Biscuits 300 g|25-40', 'Oat Cookies 250 g|85-140', 'Jeera Biscuits 200 g|28-48', 'Coconut Cookies 200 g|48-80', 'Cashew Cookies 200 g|85-135', 'Wafer Rolls 150 g|35-58'],
      specs: { Flavour: ['Original', 'Chocolate', 'Butter', 'Cumin', 'Coconut'], Pack: ['Family pack', 'Everyday pack'] }, facets: ['Flavour'],
      blurb: '{name} is crisp, fresh and perfect with chai.', bullets: ['Baked fresh', 'Resealable pack', 'No artificial colours', 'FSSAI licensed'] },
    { id: 'NAM', category: 'namkeen-chips', count: 14, type: 'SIMPLE', brands: ['crunchbox', 'tastekraft'], gst: 12, hsn: '2106', price: [10, 220], ending: 9, weightG: [50, 400], popularity: 2.2, stock: [60, 260], palette: ['9a3412', 'fdba74'],
      models: ['Potato Chips Classic Salted 90 g|20-30', 'Potato Chips Masala 90 g|20-30', 'Aloo Bhujia 200 g|45-70', 'Navratan Mixture 200 g|50-80', 'Roasted Makhana 80 g|90-150', 'Salted Peanuts 200 g|45-75', 'Popcorn Butter 100 g|35-60', 'Nachos Cheese 150 g|55-90', 'Moong Dal Namkeen 200 g|50-80', 'Banana Chips 200 g|60-110', 'Khakhra Methi 200 g|55-90', 'Roasted Chana 200 g|42-70', 'Sev Bhujia 400 g|90-150', 'Trail Mix 200 g|140-220'],
      specs: { Flavour: ['Classic salted', 'Masala', 'Cheese', 'Tangy'], Pack: ['Single serve', 'Family pack'] }, facets: ['Flavour'],
      blurb: '{name} is a crunchy, flavourful snack for any time of day.', bullets: ['Freshly packed', 'No trans fat', 'Nitrogen-flushed pack', 'FSSAI licensed'] },
    { id: 'TEA', category: 'tea-coffee', count: 10, type: 'VARIABLE', brands: ['sipwell'], gst: 5, hsn: '0902', price: [95, 480], ending: 9, weightG: [250, 260], popularity: 1.8, stock: [40, 180], palette: ['3f6212', 'ecfccb'],
      models: ['Assam CTC Tea|110-190', 'Darjeeling Black Tea|220-380', 'Masala Chai Tea|130-210', 'Green Tea Leaves|180-320', 'Tulsi Green Tea|160-280', 'Filter Coffee Powder|190-320', 'Instant Coffee Granules|240-480', 'Kashmiri Kahwa Tea|240-420', 'Earl Grey Tea|210-360', 'Lemongrass Herbal Tea|170-290'],
      axes: [PACK_TEA], maxVariants: 2,
      specs: { Type: ['CTC', 'Orthodox leaf', 'Herbal', 'Roast and ground'], Caffeine: ['Contains caffeine', 'Caffeine free'] }, facets: ['Type'],
      blurb: '{name} gives a fresh, aromatic cup every time.', bullets: ['Sealed for aroma', 'Garden-sourced', 'Resealable pouch', 'FSSAI licensed'] },
    { id: 'JUI', category: 'juices-drinks', count: 8, type: 'SIMPLE', brands: ['sipwell', 'kisan-valley'], gst: 12, hsn: '2009', price: [20, 150], ending: 9, weightG: [200, 1100], popularity: 1.6, stock: [40, 200], palette: ['c2410c', 'fed7aa'],
      models: ['Mixed Fruit Juice 1 L|85-120', 'Orange Juice 1 L|88-125', 'Apple Juice 1 L|92-130', 'Coconut Water 200 ml|35-55', 'Mango Drink 200 ml|20-30', 'Guava Juice 1 L|85-120', 'Jeera Masala Soda 250 ml|22-35', 'Lemon Iced Tea 250 ml|30-48'],
      specs: { Pack: ['Tetra pack', 'PET bottle', 'Glass bottle'], Sugar: ['No added sugar', 'Contains sugar'] }, facets: ['Sugar'],
      blurb: '{name} is a refreshing, ready-to-drink choice.', bullets: ['Serve chilled', 'No artificial colours', 'Shake well', 'FSSAI licensed'] },
    { id: 'SOD', category: 'juices-drinks', count: 4, type: 'SIMPLE', brands: ['sipwell'], gst: 28, hsn: '2202', price: [35, 110], ending: 9, weightG: [700, 2300], popularity: 1.2, stock: [50, 220], palette: ['991b1b', 'fecaca'],
      models: ['Cola 750 ml|38-48', 'Lemon Soda 750 ml|35-45', 'Orange Fizz 2 L|85-110', 'Ginger Ale 500 ml|55-80'],
      specs: { Pack: ['PET bottle', 'Can'] }, facets: [],
      blurb: '{name} is a fizzy favourite for get-togethers.', bullets: ['Serve chilled', 'Contains carbonated water', 'Recyclable bottle', 'FSSAI licensed'] },
    { id: 'CER', category: 'breakfast-cereals', count: 8, type: 'SIMPLE', brands: ['nutrimeal'], gst: 18, hsn: '1904', price: [95, 480], ending: 9, weightG: [250, 1050], popularity: 1.4, stock: [40, 160], palette: ['a16207', 'fef08a'],
      models: ['Rolled Oats 1 kg|165-240', 'Instant Oats 500 g|95-150', 'Corn Flakes 475 g|150-210', 'Fruit and Nut Muesli 500 g|220-320', 'Chocolate Cereal 300 g|140-210', 'Peanut Butter Granola 400 g|260-390', 'Millet Muesli 400 g|210-310', 'Honey Wheat Flakes 400 g|170-250'],
      specs: { Type: ['Whole grain', 'Multigrain', 'Millet-based'], Sugar: ['Low sugar', 'Regular'] }, facets: ['Type'],
      blurb: '{name} makes a quick, wholesome breakfast.', bullets: ['High in fibre', 'Resealable pack', 'No artificial colours', 'FSSAI licensed'] },
    { id: 'SAU', category: 'sauces-spreads', count: 10, type: 'SIMPLE', brands: ['tastekraft', 'spiceroute'], gst: 12, hsn: '2103', price: [45, 380], ending: 9, weightG: [180, 1050], popularity: 1.4, stock: [40, 160], palette: ['b91c1c', 'fee2e2'],
      models: ['Tomato Ketchup 950 g|110-160', 'Mayonnaise 250 g|75-120', 'Mixed Fruit Jam 500 g|120-190', 'Peanut Butter Crunchy 500 g|180-290', 'Mango Pickle 400 g|95-160', 'Green Chilli Sauce 200 g|45-80', 'Schezwan Chutney 250 g|85-140', 'Honey 500 g|210-380', 'Mint Chutney 200 g|55-95', 'Chocolate Spread 350 g|190-320'],
      specs: { Flavour: ['Classic', 'Spicy', 'Sweet', 'Tangy'], Pack: ['Glass jar', 'PET jar', 'Squeeze bottle'] }, facets: ['Flavour'],
      blurb: '{name} adds taste to every meal.', bullets: ['No artificial colours', 'Refrigerate after opening', 'Tamper-evident seal', 'FSSAI licensed'] },
    { id: 'NOO', category: 'noodles-pasta', count: 6, type: 'SIMPLE', brands: ['tastekraft', 'nutrimeal'], gst: 12, hsn: '1902', price: [12, 260], ending: 9, weightG: [60, 500], popularity: 1.6, stock: [60, 240], palette: ['ca8a04', 'fef9c3'],
      models: ['Instant Masala Noodles 70 g|12-18', 'Atta Noodles Pack of 4|60-98', 'Penne Pasta 500 g|80-130', 'Spaghetti 500 g|82-135', 'Vermicelli 400 g|35-58', 'Tomato Soup Mix 50 g|25-45'],
      specs: { Type: ['Instant', 'Dry pasta', 'Mix'], Cook: ['Ready in 2 minutes', 'Boil 8-10 minutes'] }, facets: ['Type'],
      blurb: '{name} makes dinner quick and easy.', bullets: ['Ready quickly', 'Contains tastemaker sachet where applicable', 'No added MSG on select packs', 'FSSAI licensed'] },
    { id: 'CLN', category: 'cleaning-supplies', count: 8, type: 'SIMPLE', brands: ['homeglow'], gst: 18, hsn: '3402', price: [45, 560], ending: 9, weightG: [250, 3200], popularity: 1.3, stock: [30, 140], palette: ['0e7490', 'cffafe'],
      models: ['Detergent Powder 2 kg|165-260', 'Liquid Detergent 1 L|190-330', 'Dishwash Gel 750 ml|110-180', 'Floor Cleaner 1 L|120-210', 'Toilet Cleaner 500 ml|78-130', 'Garbage Bags Medium Pack of 30|60-110', 'Kitchen Tissue Roll Pack of 2|85-150', 'Glass Cleaner 500 ml|95-160'],
      specs: { Fragrance: ['Lemon', 'Lavender', 'Pine', 'Fragrance free'], Pack: ['Pouch', 'Bottle', 'Carton'] }, facets: ['Fragrance'],
      blurb: '{name} tackles everyday dirt with less effort.', bullets: ['Dermatologically tested', 'Biodegradable surfactants', 'Keep away from children', 'Safe for regular use'] },
    { id: 'PCR', category: 'personal-care', count: 8, type: 'SIMPLE', brands: ['homeglow'], gst: 18, hsn: '3401', price: [22, 420], ending: 9, weightG: [90, 800], popularity: 1.3, stock: [30, 140], palette: ['7e22ce', 'f3e8ff'],
      models: ['Bathing Soap Pack of 4|120-200', 'Shampoo 340 ml|160-280', 'Toothpaste 200 g|85-150', 'Hand Wash 250 ml|75-130', 'Body Lotion 400 ml|190-330', 'Face Wash 100 ml|110-190', 'Sanitary Pads Pack of 20|85-150', 'Deodorant 150 ml|140-250'],
      specs: { Type: ['Everyday', 'Sensitive', 'Herbal'], Pack: ['Single', 'Value pack'] }, facets: ['Type'],
      blurb: '{name} keeps you fresh and cared for.', bullets: ['Dermatologically tested', 'Cruelty-free', 'Paraben-free formulas where stated', 'Check ingredients before use'] },
  ],
  coupons: standardCoupons('FB', { bigOrderRupees: 999, freeShipMin: 299 }),
  banners: [
    { title: 'Fresh in 2 hours', subtitle: 'Fruits, vegetables and dairy delivered to your door', cta: 'Shop fresh', link: '/products?category=fruits-vegetables' },
    { title: 'Monthly staples', subtitle: 'Stock up on atta, rice and dals at everyday low prices', cta: 'Shop staples', link: '/products?category=staples' },
    { title: 'Snack time', subtitle: 'Biscuits, namkeen and cold drinks', cta: 'Shop snacks', link: '/products?category=snacks' },
  ],
};
