import type { TenantSpec } from '../types';
import { axis, colourAxis, sizeAxis, STAFF_TEMPLATE, standardCoupons } from './common';

const SIZES_ALPHA = ['S', 'M', 'L', 'XL', 'XXL'];
const SIZES_WOMEN = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

/** StyleVerse Fashion: clothing, footwear and accessories. All brand names are fictional. */
export const STYLEVERSE: TenantSpec = {
  slug: 'styleverse-fashion',
  tag: 'SVF',
  businessName: 'StyleVerse Fashion',
  legalName: 'StyleVerse Fashion Retail LLP',
  gstin: '24STYLV0002B1Z7',
  storefrontTheme: 'famms',
  themeTemplate: 'fashion',
  brandColor: 'be123c',
  accentColor: 'f59e0b',
  tagline: 'Everyday style, festive flair',
  storeName: 'StyleVerse Fashion',
  contactPhone: '+917000022001',
  supportPhone: '+917000022002',
  reviewNoun: 'outfit',
  homeStateShare: 0.28,
  weekendBoost: 1.35,
  freeShippingRupees: 799,
  shippingRupees: 79,
  paymentMix: [['UPI', 36], ['CARD', 20], ['COD', 28], ['WALLET', 9], ['NETBANKING', 7]],
  lineMix: [[1, 40], [2, 34], [3, 18], [4, 8]],
  qtyMix: [[1, 80], [2, 17], [3, 3]],
  staff: STAFF_TEMPLATE([['Mehul', 'Trivedi'], ['Rina', 'Parekh'], ['Jignesh', 'Modi'], ['Hetal', 'Vora'], ['Chirag', 'Soni'], ['Ishita', 'Bakshi']]),
  warehouses: [
    { code: 'WH-SUR-01', name: 'Surat Textile Hub', line1: 'Shop 9, Ring Road Textile Market', city: 'Surat', state: 'Gujarat', stateCode: 'GJ', postal: '395002', lat: '21.1952000', lng: '72.8311000' },
    { code: 'WH-GGN-01', name: 'Gurugram Fulfilment Centre', line1: 'Unit 31, Sector 37 Industrial Area', city: 'Gurugram', state: 'Haryana', stateCode: 'HR', postal: '122001', lat: '28.4089000', lng: '77.0378000' },
  ],
  brands: [
    { slug: 'urbanweave', name: 'Urbanweave', description: 'Contemporary menswear for work and weekends.' },
    { slug: 'denimora', name: 'Denimora', description: 'Denim and casual staples with a modern fit.' },
    { slug: 'kurtaaz', name: 'Kurtaaz', description: 'Everyday and festive ethnic wear.' },
    { slug: 'saffron-loom', name: 'Saffron Loom', description: 'Handloom-inspired sarees and ethnic fabrics.' },
    { slug: 'westline', name: 'Westline', description: 'Western tops, dresses and co-ords for women.' },
    { slug: 'tinythreads', name: 'TinyThreads', description: 'Soft, safe clothing for kids.' },
    { slug: 'stridewell', name: 'Stridewell', description: 'Comfortable footwear for every day.' },
    { slug: 'zariwala', name: 'Zariwala', description: 'Festive wear with zari and embroidery.' },
    { slug: 'carryall', name: 'Carryall', description: 'Bags and travel essentials.' },
    { slug: 'glimmerly', name: 'Glimmerly', description: 'Fashion accessories that finish the look.' },
  ],
  categories: [
    { slug: 'men', name: 'Men', description: 'Clothing for men: casual, formal and ethnic.', children: [
      { slug: 'mens-topwear', name: "Men's Topwear", description: 'T-shirts, shirts, jackets and hoodies.' },
      { slug: 'mens-bottomwear', name: "Men's Bottomwear", description: 'Jeans, chinos and trousers.' },
      { slug: 'mens-ethnic', name: "Men's Ethnic Wear", description: 'Kurtas, kurta sets and Nehru jackets.' },
    ] },
    { slug: 'womens-ethnic', name: "Women's Ethnic Wear", description: 'Kurtas, kurtis and sarees for women.', children: [
      { slug: 'womens-kurtas', name: 'Kurtas & Kurtis', description: 'Everyday and festive kurtas.' },
      { slug: 'sarees', name: 'Sarees', description: 'Cotton, silk-blend and festive sarees.' },
    ] },
    { slug: 'womens-western-wear', name: "Women's Western Wear", description: 'Tops, dresses and co-ord sets.', children: [
      { slug: 'womens-western', name: 'Tops, Dresses & Co-ords', description: 'Western tops, dresses and co-ord sets.' },
    ] },
    { slug: 'kids', name: 'Kids', description: 'Comfortable clothing for boys and girls.', children: [
      { slug: 'kids-boys', name: 'Boys', description: 'T-shirts, shorts and kurta sets for boys.' },
      { slug: 'kids-girls', name: 'Girls', description: 'Dresses, tops and ethnic wear for girls.' },
    ] },
    { slug: 'footwear', name: 'Footwear', description: 'Shoes, sandals and slippers.', children: [
      { slug: 'mens-footwear', name: "Men's Footwear", description: 'Sneakers, formal shoes and sandals.' },
      { slug: 'womens-footwear', name: "Women's Footwear", description: 'Flats, heels and sports shoes.' },
    ] },
    { slug: 'accessories', name: 'Accessories', description: 'Bags, belts, wallets and more.', children: [
      { slug: 'bags', name: 'Bags', description: 'Handbags, backpacks and totes.' },
      { slug: 'fashion-accessories', name: 'Fashion Accessories', description: 'Belts, wallets, scarves and sunglasses.' },
    ] },
  ],
  families: [
    { id: 'MTS', category: 'mens-topwear', count: 16, type: 'VARIABLE', brands: ['urbanweave', 'denimora'], gst: 5, hsn: '6109', price: [399, 1299], ending: 99, weightG: [180, 260], popularity: 3.0, stock: [30, 120], palette: ['1f2937', 'fda4af'],
      models: ['Classic Crew Neck T-Shirt|399-699', 'Polo T-Shirt|549-999', 'Graphic Print T-Shirt|449-799', 'Henley T-Shirt|499-899', 'Oversized Drop Shoulder Tee|599-999', 'Striped Cotton T-Shirt|449-799', 'Round Neck Pack of 2|699-1099', 'Sports Dry-Fit T-Shirt|499-899'],
      axes: [sizeAxis(SIZES_ALPHA), colourAxis(['Black', 'White', 'Navy', 'Olive'])], maxVariants: 6,
      specs: { Fabric: ['100% cotton', 'Cotton blend', 'Poly-cotton', 'Moisture-wicking polyester'], Fit: ['Regular fit', 'Slim fit', 'Oversized fit'], Neck: ['Crew neck', 'Polo collar', 'Henley'] }, facets: ['Fabric', 'Fit'],
      blurb: '{name} is a wardrobe staple with a soft hand-feel and a clean, modern fit.', bullets: ['Machine washable', 'Pre-shrunk fabric', 'Colour-fast dye', 'Easy 15-day returns'] },
    { id: 'MSH', category: 'mens-topwear', count: 14, type: 'VARIABLE', brands: ['urbanweave', 'denimora'], gst: 12, hsn: '6205', price: [799, 2199], ending: 99, weightG: [220, 340], popularity: 2.0, stock: [25, 100], palette: ['0f172a', 'fcd34d'],
      models: ['Slim Fit Formal Shirt|899-1699', 'Checked Casual Shirt|799-1499', 'Linen Blend Shirt|1199-2199', 'Oxford Button-Down Shirt|999-1799', 'Denim Shirt|1099-1999', 'Printed Resort Shirt|899-1599', 'Mandarin Collar Shirt|899-1599'],
      axes: [sizeAxis(SIZES_ALPHA), colourAxis(['White', 'Sky Blue', 'Charcoal'])], maxVariants: 6,
      specs: { Fabric: ['Cotton', 'Linen blend', 'Cotton-poly blend'], Fit: ['Slim fit', 'Regular fit'], Sleeve: ['Full sleeve', 'Half sleeve'] }, facets: ['Fabric', 'Fit'],
      blurb: '{name} is tailored for a sharp look from office hours to dinner.', bullets: ['Wrinkle-resistant finish', 'Reinforced stitching', 'Mother-of-pearl style buttons', 'Easy 15-day returns'] },
    { id: 'MJK', category: 'mens-topwear', count: 8, type: 'VARIABLE', brands: ['urbanweave', 'denimora'], gst: 12, hsn: '6201', price: [1299, 3999], ending: 99, weightG: [450, 900], popularity: 1.0, stock: [15, 60], palette: ['111827', 'fb923c'],
      models: ['Zip-Up Hoodie|1299-2299', 'Pullover Hoodie|1199-1999', 'Bomber Jacket|1999-3499', 'Denim Jacket|1999-3299'],
      axes: [sizeAxis(SIZES_ALPHA), colourAxis(['Black', 'Grey Melange', 'Navy'])], maxVariants: 5,
      specs: { Fabric: ['Fleece', 'Cotton terry', 'Denim', 'Nylon shell'], Fit: ['Regular fit', 'Relaxed fit'] }, facets: ['Fabric'],
      blurb: '{name} keeps you warm without the bulk.', bullets: ['Brushed fleece lining', 'Ribbed cuffs and hem', 'Machine washable', 'Easy 15-day returns'] },
    { id: 'MBT', category: 'mens-bottomwear', count: 16, type: 'VARIABLE', brands: ['denimora', 'urbanweave'], gst: 12, hsn: '6203', price: [899, 2499], ending: 99, weightG: [380, 650], popularity: 2.2, stock: [25, 100], palette: ['1e3a8a', 'e5e7eb'],
      models: ['Slim Fit Jeans|999-1999', 'Straight Fit Jeans|999-1899', 'Stretch Chinos|899-1699', 'Cargo Trousers|1199-2199', 'Formal Trousers|999-1899', 'Jogger Pants|799-1499', 'Relaxed Fit Jeans|1099-1999', 'Pleated Trousers|1099-2099'],
      axes: [axis('Waist', ['30', '32', '34', '36']), colourAxis(['Indigo', 'Black', 'Khaki'])], maxVariants: 6,
      specs: { Fabric: ['Stretch denim', 'Cotton twill', 'Poly-viscose'], Fit: ['Slim fit', 'Straight fit', 'Relaxed fit'] }, facets: ['Fabric', 'Fit'],
      blurb: '{name} gives a flattering fit with room to move.', bullets: ['Five-pocket styling', 'Comfort stretch', 'Colour-fast wash', 'Easy 15-day returns'] },
    { id: 'MET', category: 'mens-ethnic', count: 12, type: 'VARIABLE', brands: ['kurtaaz', 'zariwala'], gst: 12, hsn: '6205', price: [799, 3999], ending: 99, weightG: [300, 700], popularity: 1.4, stock: [20, 80], palette: ['78350f', 'fde68a'],
      models: ['Cotton Kurta|799-1499', 'Kurta Pyjama Set|1299-2499', 'Nehru Jacket|1499-2999', 'Embroidered Festive Kurta|1699-3499', 'Silk Blend Kurta Set|1999-3999', 'Linen Kurta|999-1799'],
      axes: [sizeAxis(SIZES_ALPHA), colourAxis(['Cream', 'Maroon', 'Teal'])], maxVariants: 5,
      specs: { Fabric: ['Cotton', 'Silk blend', 'Linen blend'], Occasion: ['Daily wear', 'Festive', 'Wedding guest'] }, facets: ['Occasion'],
      blurb: '{name} blends tradition with a comfortable modern cut.', bullets: ['Breathable fabric', 'Neat finishing', 'Dry clean or gentle wash', 'Easy 15-day returns'] },
    { id: 'WKU', category: 'womens-kurtas', count: 22, type: 'VARIABLE', brands: ['kurtaaz', 'zariwala', 'saffron-loom'], gst: 5, hsn: '6104', price: [499, 1999], ending: 99, weightG: [220, 420], popularity: 3.2, stock: [30, 140], palette: ['9d174d', 'fbcfe8'],
      models: ['Straight Cotton Kurti|499-999', 'A-Line Anarkali Kurta|799-1599', 'Printed Rayon Kurta|549-1099', 'Chikankari Kurta|999-1999', 'Kurta with Palazzo Set|899-1799', 'Embroidered Yoke Kurta|699-1399', 'Block Print Kurta|599-1199', 'Festive Kurta Set with Dupatta|1299-2499'],
      axes: [sizeAxis(SIZES_WOMEN), colourAxis(['Indigo', 'Mustard', 'Rose Pink'])], maxVariants: 6,
      specs: { Fabric: ['Cotton', 'Rayon', 'Georgette', 'Cotton blend'], Pattern: ['Printed', 'Embroidered', 'Solid', 'Block print'], Sleeve: ['Three-quarter', 'Full sleeve', 'Short sleeve'] }, facets: ['Fabric', 'Pattern'],
      blurb: '{name} is easy to style for work, family gatherings and festive days.', bullets: ['Soft, breathable fabric', 'Fade-resistant colours', 'Machine washable', 'Easy 15-day returns'] },
    { id: 'SAR', category: 'sarees', count: 16, type: 'SIMPLE', brands: ['saffron-loom', 'zariwala'], gst: 5, hsn: '5407', price: [799, 4999], ending: 99, weightG: [500, 900], popularity: 1.6, stock: [15, 70], palette: ['7f1d1d', 'fde68a'],
      models: ['Cotton Handloom Saree|799-1599', 'Banarasi Silk Blend Saree|1999-4999', 'Georgette Printed Saree|899-1999', 'Chanderi Cotton Saree|1299-2599', 'Kanjeevaram Style Saree|2999-4999', 'Linen Saree|1299-2199', 'Bandhani Saree|1199-2499', 'Organza Floral Saree|1499-2999'],
      specs: { Fabric: ['Cotton', 'Silk blend', 'Georgette', 'Chanderi', 'Linen'], Occasion: ['Daily wear', 'Festive', 'Wedding', 'Office'], Blouse: ['Blouse piece included', 'Stitched blouse'] }, facets: ['Fabric', 'Occasion'],
      blurb: '{name} drapes beautifully and is finished with a coordinated blouse piece.', bullets: ['6.3 metres including blouse piece', 'Dry clean recommended', 'Colour may vary slightly by screen', 'Easy 15-day returns'] },
    { id: 'WWE', category: 'womens-western', count: 18, type: 'VARIABLE', brands: ['westline', 'denimora'], gst: 12, hsn: '6204', price: [499, 2499], ending: 99, weightG: [180, 450], popularity: 2.4, stock: [25, 110], palette: ['831843', 'f9a8d4'],
      models: ['Floral Midi Dress|899-1899', 'Wrap Dress|999-1999', 'Ribbed Crop Top|499-899', 'Satin Cami Top|549-999', 'Co-ord Set|1299-2499', 'High-Rise Mom Jeans|999-1899', 'Pleated Midi Skirt|699-1499', 'Peplum Top|599-1099', 'Boyfriend Shirt|799-1399'],
      axes: [sizeAxis(SIZES_WOMEN), colourAxis(['Black', 'Sage', 'Blush'])], maxVariants: 6,
      specs: { Fabric: ['Rayon', 'Cotton', 'Satin', 'Polyester crepe'], Fit: ['Regular fit', 'Relaxed fit', 'Fit and flare'] }, facets: ['Fabric', 'Fit'],
      blurb: '{name} is an easy, flattering pick for brunches, work and weekends.', bullets: ['Lightweight fabric', 'True-to-size fit', 'Machine washable', 'Easy 15-day returns'] },
    { id: 'KBY', category: 'kids-boys', count: 10, type: 'VARIABLE', brands: ['tinythreads', 'kurtaaz'], gst: 5, hsn: '6109', price: [349, 1299], ending: 99, weightG: [120, 300], popularity: 1.2, stock: [30, 120], palette: ['0c4a6e', 'fde047'],
      models: ['Cotton T-Shirt Pack of 3|599-999', 'Printed Shorts Set|449-899', 'Kurta Pyjama Set|699-1299', 'Hooded Sweatshirt|549-999', 'Denim Dungarees|649-1199'],
      axes: [axis('Age', ['2-3 Y', '4-5 Y', '6-7 Y', '8-9 Y']), colourAxis(['Blue', 'Red', 'Green'])], maxVariants: 5,
      specs: { Fabric: ['100% cotton', 'Cotton fleece', 'Cotton blend'], Care: ['Machine wash', 'Gentle wash'] }, facets: ['Fabric'],
      blurb: '{name} is soft on skin and tough enough for play.', bullets: ['Skin-friendly dyes', 'Easy on-off design', 'Machine washable', 'Easy 15-day returns'] },
    { id: 'KGL', category: 'kids-girls', count: 10, type: 'VARIABLE', brands: ['tinythreads', 'zariwala'], gst: 5, hsn: '6104', price: [399, 1999], ending: 99, weightG: [120, 350], popularity: 1.2, stock: [30, 110], palette: ['86198f', 'fbcfe8'],
      models: ['Party Frock|699-1499', 'Lehenga Choli Set|1299-1999', 'Cotton Frock|399-899', 'Leggings Pack of 2|399-699', 'Kurti with Leggings|599-1199'],
      axes: [axis('Age', ['2-3 Y', '4-5 Y', '6-7 Y', '8-9 Y']), colourAxis(['Pink', 'Yellow', 'Lilac'])], maxVariants: 5,
      specs: { Fabric: ['Cotton', 'Net and satin', 'Cotton blend'], Occasion: ['Daily wear', 'Party', 'Festive'] }, facets: ['Occasion'],
      blurb: '{name} is comfortable for all-day wear and pretty enough for celebrations.', bullets: ['Soft inner lining', 'Secure fastenings', 'Machine washable', 'Easy 15-day returns'] },
    { id: 'MFW', category: 'mens-footwear', count: 16, type: 'VARIABLE', brands: ['stridewell', 'urbanweave'], gst: 12, hsn: '6403', price: [599, 2999], ending: 99, weightG: [350, 750], popularity: 2.0, stock: [20, 90], palette: ['262626', 'fb923c'],
      models: ['Lace-Up Sneakers|999-1999', 'Running Shoes|1299-2799', 'Formal Derby Shoes|1499-2999', 'Leather Loafers|1299-2499', 'Flip Flops|299-599', 'Sports Sandals|599-1199', 'Casual Slip-Ons|699-1399', 'Canvas Shoes|799-1499'],
      axes: [axis('UK size', ['6', '7', '8', '9', '10']), colourAxis(['Black', 'Tan', 'White'])], maxVariants: 6,
      specs: { Material: ['Mesh and synthetic', 'Genuine leather', 'Canvas', 'EVA'], Closure: ['Lace-up', 'Slip-on', 'Velcro'] }, facets: ['Material'],
      blurb: '{name} gives all-day comfort with a cushioned footbed and grippy sole.', bullets: ['Lightweight sole', 'Breathable lining', 'Anti-skid outsole', 'Easy 15-day returns'] },
    { id: 'WFW', category: 'womens-footwear', count: 14, type: 'VARIABLE', brands: ['stridewell', 'westline'], gst: 12, hsn: '6402', price: [499, 2499], ending: 99, weightG: [250, 600], popularity: 1.8, stock: [20, 90], palette: ['581c87', 'f5d0fe'],
      models: ['Ballet Flats|499-999', 'Block Heel Sandals|799-1599', 'Wedge Sandals|899-1699', 'Sports Running Shoes|1299-2499', 'Kolhapuri Sandals|599-1199', 'Platform Sneakers|999-1899', 'Slides|399-799'],
      axes: [axis('UK size', ['3', '4', '5', '6', '7']), colourAxis(['Black', 'Beige', 'Rose Gold'])], maxVariants: 6,
      specs: { Material: ['Synthetic', 'Faux leather', 'Fabric', 'EVA'], Heel: ['Flat', 'Block heel', 'Wedge'] }, facets: ['Material', 'Heel'],
      blurb: '{name} is cushioned for long days and finished with a polished look.', bullets: ['Padded footbed', 'Non-slip sole', 'Lightweight', 'Easy 15-day returns'] },
    { id: 'BAG', category: 'bags', count: 12, type: 'SIMPLE', brands: ['carryall', 'glimmerly'], gst: 18, hsn: '4202', price: [599, 3499], ending: 99, weightG: [250, 900], popularity: 1.3, stock: [15, 70], palette: ['422006', 'fed7aa'],
      models: ['Everyday Tote Bag|799-1699', 'Laptop Backpack 30L|999-2199', 'Sling Bag|599-1199', 'Duffel Gym Bag|899-1899', 'Faux Leather Handbag|1199-2499', 'Mini Crossbody Bag|799-1599'],
      specs: { Material: ['Canvas', 'Faux leather', 'Nylon', 'Polyester'], Capacity: ['10 L', '20 L', '30 L'] }, facets: ['Material'],
      blurb: '{name} is roomy, well organised and built to last.', bullets: ['Water-resistant lining', 'Sturdy zips', 'Padded straps', 'Easy 15-day returns'] },
    { id: 'ACC', category: 'fashion-accessories', count: 16, type: 'SIMPLE', brands: ['glimmerly', 'carryall', 'urbanweave'], gst: 18, hsn: '4203', price: [199, 1999], ending: 99, weightG: [40, 300], popularity: 1.6, stock: [30, 150], palette: ['3f3f46', 'e4e4e7'],
      models: ['Leather Belt|399-899', 'Bi-Fold Wallet|399-999', 'Polarised Sunglasses|499-1499', 'Printed Scarf|249-599', 'Beaded Necklace Set|299-899', 'Jhumka Earrings|199-599', 'Analog Wrist Watch|799-1999', 'Silk Dupatta|599-1499'],
      specs: { Material: ['Genuine leather', 'Faux leather', 'Alloy', 'Silk blend', 'Polycarbonate'], Style: ['Classic', 'Contemporary', 'Traditional'] }, facets: ['Style'],
      blurb: '{name} adds the finishing touch to your outfit.', bullets: ['Gift-ready packaging', 'Skin-safe materials', 'Lightweight', 'Easy 15-day returns'] },
  ],
  coupons: standardCoupons('SV', { bigOrderRupees: 1999, freeShipMin: 499 }),
  banners: [
    { title: 'Festive Edit', subtitle: 'Kurtas, sarees and ethnic sets with up to 50% off', cta: 'Shop festive wear', link: '/products?category=womens-ethnic' },
    { title: 'Denim Days', subtitle: 'Jeans and casuals from Rs 899', cta: 'Shop men', link: '/products?category=men' },
    { title: 'Little Stars', subtitle: 'Soft, safe styles for kids', cta: 'Shop kids', link: '/products?category=kids' },
  ],
};
